package com.wxfeng.mybatis.uniorder;

import java.math.BigDecimal;
import java.util.Date;

public class AirOrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal airOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.OUTER_AIR_ORDER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String outerAirOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.AIR_ORDER_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String airOrderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.AIR_ORDER_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String airOrderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.SHOPPING_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String shoppingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String promoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.PROMO_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String promoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.IS_PRINT_RCPT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isPrintRcpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.IS_INTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isInter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.IS_GROUP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.IS_PACKAGE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isPackage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.PAX_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short paxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.ADT_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short adtNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.INF_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short infNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.CHD_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short chdNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.CONTACT_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.CONTACT_MOBILE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String contactMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.USER_FFP_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String userFfpNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.CONTACT_EMAIL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String contactEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short channelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String secondChannelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String thirdChannelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.SITE_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String siteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal payAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String payCurreny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.EXCHANGE_RMB
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal exchangeRmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.POINT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long pointAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.CASH_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal cashAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.CASH_PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String cashPayCurreny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.COUPON_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal couponAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.COUPON_PAY_UNIT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String couponPayUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.TKT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal tktAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal taxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal agencyAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String crtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String optId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date optDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.SUB_PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String subPromoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.AIR_BUSSINESS_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String airBussinessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.VIP_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String vipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.TRIP_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String tripType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.OFFICE_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String officeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.REWARD_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String rewardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.SESSION_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.GIFT_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long giftPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.FFP_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String ffpLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.BOOKING_FLOW_WAY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short bookingFlowWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.FARE_SOURCE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fareSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_ORDER_INFO.AIR_ETDZ_FAIL_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Integer airEtdzFailNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_ORDER_NO
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAirOrderNo() {
        return airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_ORDER_NO
     *
     * @param airOrderNo the value for UNIORDER.AIR_ORDER_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirOrderNo(BigDecimal airOrderNo) {
        this.airOrderNo = airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.OUTER_AIR_ORDER
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.OUTER_AIR_ORDER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOuterAirOrder() {
        return outerAirOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.OUTER_AIR_ORDER
     *
     * @param outerAirOrder the value for UNIORDER.AIR_ORDER_INFO.OUTER_AIR_ORDER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOuterAirOrder(String outerAirOrder) {
        this.outerAirOrder = outerAirOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_ORDER_STATUS
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.AIR_ORDER_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getAirOrderStatus() {
        return airOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_ORDER_STATUS
     *
     * @param airOrderStatus the value for UNIORDER.AIR_ORDER_INFO.AIR_ORDER_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirOrderStatus(String airOrderStatus) {
        this.airOrderStatus = airOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_ORDER_TYPE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.AIR_ORDER_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getAirOrderType() {
        return airOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_ORDER_TYPE
     *
     * @param airOrderType the value for UNIORDER.AIR_ORDER_INFO.AIR_ORDER_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirOrderType(String airOrderType) {
        this.airOrderType = airOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.SHOPPING_TYPE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.SHOPPING_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getShoppingType() {
        return shoppingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.SHOPPING_TYPE
     *
     * @param shoppingType the value for UNIORDER.AIR_ORDER_INFO.SHOPPING_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setShoppingType(String shoppingType) {
        this.shoppingType = shoppingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.PAY_TYPE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.PAY_TYPE
     *
     * @param payType the value for UNIORDER.AIR_ORDER_INFO.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.PROMO_TYPE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPromoType() {
        return promoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.PROMO_TYPE
     *
     * @param promoType the value for UNIORDER.AIR_ORDER_INFO.PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPromoType(String promoType) {
        this.promoType = promoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.PROMO_ID
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.PROMO_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPromoId() {
        return promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.PROMO_ID
     *
     * @param promoId the value for UNIORDER.AIR_ORDER_INFO.PROMO_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPromoId(String promoId) {
        this.promoId = promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.IS_PRINT_RCPT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.IS_PRINT_RCPT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsPrintRcpt() {
        return isPrintRcpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.IS_PRINT_RCPT
     *
     * @param isPrintRcpt the value for UNIORDER.AIR_ORDER_INFO.IS_PRINT_RCPT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsPrintRcpt(Short isPrintRcpt) {
        this.isPrintRcpt = isPrintRcpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.IS_INTER
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.IS_INTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsInter() {
        return isInter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.IS_INTER
     *
     * @param isInter the value for UNIORDER.AIR_ORDER_INFO.IS_INTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsInter(Short isInter) {
        this.isInter = isInter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.IS_GROUP
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.IS_GROUP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsGroup() {
        return isGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.IS_GROUP
     *
     * @param isGroup the value for UNIORDER.AIR_ORDER_INFO.IS_GROUP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsGroup(Short isGroup) {
        this.isGroup = isGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.IS_PACKAGE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.IS_PACKAGE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsPackage() {
        return isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.IS_PACKAGE
     *
     * @param isPackage the value for UNIORDER.AIR_ORDER_INFO.IS_PACKAGE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsPackage(Short isPackage) {
        this.isPackage = isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.PAX_NUM
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.PAX_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getPaxNum() {
        return paxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.PAX_NUM
     *
     * @param paxNum the value for UNIORDER.AIR_ORDER_INFO.PAX_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxNum(Short paxNum) {
        this.paxNum = paxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.ADT_NUM
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.ADT_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getAdtNum() {
        return adtNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.ADT_NUM
     *
     * @param adtNum the value for UNIORDER.AIR_ORDER_INFO.ADT_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAdtNum(Short adtNum) {
        this.adtNum = adtNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.INF_NUM
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.INF_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getInfNum() {
        return infNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.INF_NUM
     *
     * @param infNum the value for UNIORDER.AIR_ORDER_INFO.INF_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setInfNum(Short infNum) {
        this.infNum = infNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.CHD_NUM
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.CHD_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getChdNum() {
        return chdNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.CHD_NUM
     *
     * @param chdNum the value for UNIORDER.AIR_ORDER_INFO.CHD_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChdNum(Short chdNum) {
        this.chdNum = chdNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.CONTACT_NAME
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.CONTACT_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.CONTACT_NAME
     *
     * @param contactName the value for UNIORDER.AIR_ORDER_INFO.CONTACT_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.CONTACT_MOBILE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.CONTACT_MOBILE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.CONTACT_MOBILE
     *
     * @param contactMobile the value for UNIORDER.AIR_ORDER_INFO.CONTACT_MOBILE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.USER_FFP_NO
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.USER_FFP_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getUserFfpNo() {
        return userFfpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.USER_FFP_NO
     *
     * @param userFfpNo the value for UNIORDER.AIR_ORDER_INFO.USER_FFP_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setUserFfpNo(String userFfpNo) {
        this.userFfpNo = userFfpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.CONTACT_EMAIL
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.CONTACT_EMAIL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.CONTACT_EMAIL
     *
     * @param contactEmail the value for UNIORDER.AIR_ORDER_INFO.CONTACT_EMAIL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.ORDER_NO
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.ORDER_NO
     *
     * @param orderNo the value for UNIORDER.AIR_ORDER_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.CHANNEL_NO
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.CHANNEL_NO
     *
     * @param channelNo the value for UNIORDER.AIR_ORDER_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChannelNo(Short channelNo) {
        this.channelNo = channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSecondChannelNo() {
        return secondChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @param secondChannelNo the value for UNIORDER.AIR_ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSecondChannelNo(String secondChannelNo) {
        this.secondChannelNo = secondChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getThirdChannelNo() {
        return thirdChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @param thirdChannelNo the value for UNIORDER.AIR_ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setThirdChannelNo(String thirdChannelNo) {
        this.thirdChannelNo = thirdChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.SITE_CODE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.SITE_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSiteCode() {
        return siteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.SITE_CODE
     *
     * @param siteCode the value for UNIORDER.AIR_ORDER_INFO.SITE_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.PAY_AMT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getPayAmt() {
        return payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.PAY_AMT
     *
     * @param payAmt the value for UNIORDER.AIR_ORDER_INFO.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayAmt(BigDecimal payAmt) {
        this.payAmt = payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.PAY_CURRENY
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPayCurreny() {
        return payCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.PAY_CURRENY
     *
     * @param payCurreny the value for UNIORDER.AIR_ORDER_INFO.PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayCurreny(String payCurreny) {
        this.payCurreny = payCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.EXCHANGE_RMB
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.EXCHANGE_RMB
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getExchangeRmb() {
        return exchangeRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.EXCHANGE_RMB
     *
     * @param exchangeRmb the value for UNIORDER.AIR_ORDER_INFO.EXCHANGE_RMB
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setExchangeRmb(BigDecimal exchangeRmb) {
        this.exchangeRmb = exchangeRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.POINT_AMT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.POINT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getPointAmt() {
        return pointAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.POINT_AMT
     *
     * @param pointAmt the value for UNIORDER.AIR_ORDER_INFO.POINT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPointAmt(Long pointAmt) {
        this.pointAmt = pointAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.CASH_AMT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.CASH_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getCashAmt() {
        return cashAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.CASH_AMT
     *
     * @param cashAmt the value for UNIORDER.AIR_ORDER_INFO.CASH_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCashAmt(BigDecimal cashAmt) {
        this.cashAmt = cashAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.CASH_PAY_CURRENY
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.CASH_PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCashPayCurreny() {
        return cashPayCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.CASH_PAY_CURRENY
     *
     * @param cashPayCurreny the value for UNIORDER.AIR_ORDER_INFO.CASH_PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCashPayCurreny(String cashPayCurreny) {
        this.cashPayCurreny = cashPayCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.COUPON_AMT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.COUPON_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getCouponAmt() {
        return couponAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.COUPON_AMT
     *
     * @param couponAmt the value for UNIORDER.AIR_ORDER_INFO.COUPON_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCouponAmt(BigDecimal couponAmt) {
        this.couponAmt = couponAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.COUPON_PAY_UNIT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.COUPON_PAY_UNIT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCouponPayUnit() {
        return couponPayUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.COUPON_PAY_UNIT
     *
     * @param couponPayUnit the value for UNIORDER.AIR_ORDER_INFO.COUPON_PAY_UNIT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCouponPayUnit(String couponPayUnit) {
        this.couponPayUnit = couponPayUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.TKT_AMT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.TKT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getTktAmt() {
        return tktAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.TKT_AMT
     *
     * @param tktAmt the value for UNIORDER.AIR_ORDER_INFO.TKT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTktAmt(BigDecimal tktAmt) {
        this.tktAmt = tktAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.TAX_AMT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getTaxAmt() {
        return taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.TAX_AMT
     *
     * @param taxAmt the value for UNIORDER.AIR_ORDER_INFO.TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTaxAmt(BigDecimal taxAmt) {
        this.taxAmt = taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.AGENCY_AMT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAgencyAmt() {
        return agencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.AGENCY_AMT
     *
     * @param agencyAmt the value for UNIORDER.AIR_ORDER_INFO.AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAgencyAmt(BigDecimal agencyAmt) {
        this.agencyAmt = agencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.REMARK
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.REMARK
     *
     * @param remark the value for UNIORDER.AIR_ORDER_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.IS_VALID
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.IS_VALID
     *
     * @param isValid the value for UNIORDER.AIR_ORDER_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsValid(Short isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.CRT_ID
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCrtId() {
        return crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.CRT_ID
     *
     * @param crtId the value for UNIORDER.AIR_ORDER_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.CRT_DT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.CRT_DT
     *
     * @param crtDt the value for UNIORDER.AIR_ORDER_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtDt(Date crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.OPT_ID
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.OPT_ID
     *
     * @param optId the value for UNIORDER.AIR_ORDER_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptId(String optId) {
        this.optId = optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.OPT_DT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getOptDt() {
        return optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.OPT_DT
     *
     * @param optDt the value for UNIORDER.AIR_ORDER_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptDt(Date optDt) {
        this.optDt = optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.VERSION
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.VERSION
     *
     * @param version the value for UNIORDER.AIR_ORDER_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.SUB_PROMO_TYPE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.SUB_PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSubPromoType() {
        return subPromoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.SUB_PROMO_TYPE
     *
     * @param subPromoType the value for UNIORDER.AIR_ORDER_INFO.SUB_PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSubPromoType(String subPromoType) {
        this.subPromoType = subPromoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_BUSSINESS_TYPE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.AIR_BUSSINESS_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getAirBussinessType() {
        return airBussinessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_BUSSINESS_TYPE
     *
     * @param airBussinessType the value for UNIORDER.AIR_ORDER_INFO.AIR_BUSSINESS_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirBussinessType(String airBussinessType) {
        this.airBussinessType = airBussinessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.VIP_CODE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.VIP_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getVipCode() {
        return vipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.VIP_CODE
     *
     * @param vipCode the value for UNIORDER.AIR_ORDER_INFO.VIP_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setVipCode(String vipCode) {
        this.vipCode = vipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.TRIP_TYPE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.TRIP_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getTripType() {
        return tripType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.TRIP_TYPE
     *
     * @param tripType the value for UNIORDER.AIR_ORDER_INFO.TRIP_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTripType(String tripType) {
        this.tripType = tripType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.OFFICE_NO
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.OFFICE_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOfficeNo() {
        return officeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.OFFICE_NO
     *
     * @param officeNo the value for UNIORDER.AIR_ORDER_INFO.OFFICE_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOfficeNo(String officeNo) {
        this.officeNo = officeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.REWARD_CODE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.REWARD_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRewardCode() {
        return rewardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.REWARD_CODE
     *
     * @param rewardCode the value for UNIORDER.AIR_ORDER_INFO.REWARD_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRewardCode(String rewardCode) {
        this.rewardCode = rewardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.SESSION_ID
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.SESSION_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.SESSION_ID
     *
     * @param sessionId the value for UNIORDER.AIR_ORDER_INFO.SESSION_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.GIFT_POINT
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.GIFT_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getGiftPoint() {
        return giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.GIFT_POINT
     *
     * @param giftPoint the value for UNIORDER.AIR_ORDER_INFO.GIFT_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setGiftPoint(Long giftPoint) {
        this.giftPoint = giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.FFP_LEVEL
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.FFP_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFfpLevel() {
        return ffpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.FFP_LEVEL
     *
     * @param ffpLevel the value for UNIORDER.AIR_ORDER_INFO.FFP_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFfpLevel(String ffpLevel) {
        this.ffpLevel = ffpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.BOOKING_FLOW_WAY
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.BOOKING_FLOW_WAY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getBookingFlowWay() {
        return bookingFlowWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.BOOKING_FLOW_WAY
     *
     * @param bookingFlowWay the value for UNIORDER.AIR_ORDER_INFO.BOOKING_FLOW_WAY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setBookingFlowWay(Short bookingFlowWay) {
        this.bookingFlowWay = bookingFlowWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.FARE_SOURCE
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.FARE_SOURCE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFareSource() {
        return fareSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.FARE_SOURCE
     *
     * @param fareSource the value for UNIORDER.AIR_ORDER_INFO.FARE_SOURCE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFareSource(String fareSource) {
        this.fareSource = fareSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_ETDZ_FAIL_NUM
     *
     * @return the value of UNIORDER.AIR_ORDER_INFO.AIR_ETDZ_FAIL_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Integer getAirEtdzFailNum() {
        return airEtdzFailNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_ORDER_INFO.AIR_ETDZ_FAIL_NUM
     *
     * @param airEtdzFailNum the value for UNIORDER.AIR_ORDER_INFO.AIR_ETDZ_FAIL_NUM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirEtdzFailNum(Integer airEtdzFailNum) {
        this.airEtdzFailNum = airEtdzFailNum;
    }
}