package com.wxfeng.mybatis.uniorder;

import java.util.Date;

public class AirPnrInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.B_PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String bPnrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.C_PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String cPnrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.OFFICE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String office;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.IATA_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String iataNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long airOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.IS_TICKETED
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isTicketed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.IS_INTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isInter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.FC_ADT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fcAdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.FC_CHD
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fcChd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.FC_INF
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fcInf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.FN_ADT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fnAdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.FN_CHD
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fnChd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.FN_INF
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fnInf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.FP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.EI
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String ei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.TC
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String tc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String crtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String optId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date optDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.RT_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date rtDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short channelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_COUNT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short etdzFailCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_MSG
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String etdzFailMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.FIRST_ENVELOP_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date firstEnvelopDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.IS_SPLIT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isSplit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PNR_INFO.RT_RESULT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String rtResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.ID
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.ID
     *
     * @param id the value for UNIORDER.AIR_PNR_INFO.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.B_PNR_NO
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.B_PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getbPnrNo() {
        return bPnrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.B_PNR_NO
     *
     * @param bPnrNo the value for UNIORDER.AIR_PNR_INFO.B_PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setbPnrNo(String bPnrNo) {
        this.bPnrNo = bPnrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.C_PNR_NO
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.C_PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getcPnrNo() {
        return cPnrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.C_PNR_NO
     *
     * @param cPnrNo the value for UNIORDER.AIR_PNR_INFO.C_PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setcPnrNo(String cPnrNo) {
        this.cPnrNo = cPnrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.OFFICE
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.OFFICE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOffice() {
        return office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.OFFICE
     *
     * @param office the value for UNIORDER.AIR_PNR_INFO.OFFICE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOffice(String office) {
        this.office = office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.IATA_NO
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.IATA_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getIataNo() {
        return iataNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.IATA_NO
     *
     * @param iataNo the value for UNIORDER.AIR_PNR_INFO.IATA_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIataNo(String iataNo) {
        this.iataNo = iataNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.AIR_ORDER_NO
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getAirOrderNo() {
        return airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.AIR_ORDER_NO
     *
     * @param airOrderNo the value for UNIORDER.AIR_PNR_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirOrderNo(Long airOrderNo) {
        this.airOrderNo = airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.ORDER_NO
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.ORDER_NO
     *
     * @param orderNo the value for UNIORDER.AIR_PNR_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.IS_TICKETED
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.IS_TICKETED
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsTicketed() {
        return isTicketed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.IS_TICKETED
     *
     * @param isTicketed the value for UNIORDER.AIR_PNR_INFO.IS_TICKETED
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsTicketed(Short isTicketed) {
        this.isTicketed = isTicketed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.IS_INTER
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.IS_INTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsInter() {
        return isInter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.IS_INTER
     *
     * @param isInter the value for UNIORDER.AIR_PNR_INFO.IS_INTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsInter(Short isInter) {
        this.isInter = isInter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.FC_ADT
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.FC_ADT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFcAdt() {
        return fcAdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.FC_ADT
     *
     * @param fcAdt the value for UNIORDER.AIR_PNR_INFO.FC_ADT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFcAdt(String fcAdt) {
        this.fcAdt = fcAdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.FC_CHD
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.FC_CHD
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFcChd() {
        return fcChd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.FC_CHD
     *
     * @param fcChd the value for UNIORDER.AIR_PNR_INFO.FC_CHD
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFcChd(String fcChd) {
        this.fcChd = fcChd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.FC_INF
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.FC_INF
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFcInf() {
        return fcInf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.FC_INF
     *
     * @param fcInf the value for UNIORDER.AIR_PNR_INFO.FC_INF
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFcInf(String fcInf) {
        this.fcInf = fcInf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.FN_ADT
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.FN_ADT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFnAdt() {
        return fnAdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.FN_ADT
     *
     * @param fnAdt the value for UNIORDER.AIR_PNR_INFO.FN_ADT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFnAdt(String fnAdt) {
        this.fnAdt = fnAdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.FN_CHD
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.FN_CHD
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFnChd() {
        return fnChd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.FN_CHD
     *
     * @param fnChd the value for UNIORDER.AIR_PNR_INFO.FN_CHD
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFnChd(String fnChd) {
        this.fnChd = fnChd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.FN_INF
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.FN_INF
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFnInf() {
        return fnInf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.FN_INF
     *
     * @param fnInf the value for UNIORDER.AIR_PNR_INFO.FN_INF
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFnInf(String fnInf) {
        this.fnInf = fnInf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.FP
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.FP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFp() {
        return fp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.FP
     *
     * @param fp the value for UNIORDER.AIR_PNR_INFO.FP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFp(String fp) {
        this.fp = fp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.EI
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.EI
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getEi() {
        return ei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.EI
     *
     * @param ei the value for UNIORDER.AIR_PNR_INFO.EI
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setEi(String ei) {
        this.ei = ei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.TC
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.TC
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getTc() {
        return tc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.TC
     *
     * @param tc the value for UNIORDER.AIR_PNR_INFO.TC
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTc(String tc) {
        this.tc = tc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.REMARK
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.REMARK
     *
     * @param remark the value for UNIORDER.AIR_PNR_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.IS_VALID
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.IS_VALID
     *
     * @param isValid the value for UNIORDER.AIR_PNR_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsValid(Short isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.CRT_ID
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCrtId() {
        return crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.CRT_ID
     *
     * @param crtId the value for UNIORDER.AIR_PNR_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.CRT_DT
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.CRT_DT
     *
     * @param crtDt the value for UNIORDER.AIR_PNR_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtDt(Date crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.OPT_ID
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.OPT_ID
     *
     * @param optId the value for UNIORDER.AIR_PNR_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptId(String optId) {
        this.optId = optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.OPT_DT
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getOptDt() {
        return optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.OPT_DT
     *
     * @param optDt the value for UNIORDER.AIR_PNR_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptDt(Date optDt) {
        this.optDt = optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.VERSION
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.VERSION
     *
     * @param version the value for UNIORDER.AIR_PNR_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.RT_DATE
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.RT_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getRtDate() {
        return rtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.RT_DATE
     *
     * @param rtDate the value for UNIORDER.AIR_PNR_INFO.RT_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRtDate(Date rtDate) {
        this.rtDate = rtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.CHANNEL_NO
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.CHANNEL_NO
     *
     * @param channelNo the value for UNIORDER.AIR_PNR_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChannelNo(Short channelNo) {
        this.channelNo = channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_COUNT
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_COUNT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getEtdzFailCount() {
        return etdzFailCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_COUNT
     *
     * @param etdzFailCount the value for UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_COUNT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setEtdzFailCount(Short etdzFailCount) {
        this.etdzFailCount = etdzFailCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_MSG
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_MSG
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getEtdzFailMsg() {
        return etdzFailMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_MSG
     *
     * @param etdzFailMsg the value for UNIORDER.AIR_PNR_INFO.ETDZ_FAIL_MSG
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setEtdzFailMsg(String etdzFailMsg) {
        this.etdzFailMsg = etdzFailMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.FIRST_ENVELOP_DT
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.FIRST_ENVELOP_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getFirstEnvelopDt() {
        return firstEnvelopDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.FIRST_ENVELOP_DT
     *
     * @param firstEnvelopDt the value for UNIORDER.AIR_PNR_INFO.FIRST_ENVELOP_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFirstEnvelopDt(Date firstEnvelopDt) {
        this.firstEnvelopDt = firstEnvelopDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.IS_SPLIT
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.IS_SPLIT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsSplit() {
        return isSplit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.IS_SPLIT
     *
     * @param isSplit the value for UNIORDER.AIR_PNR_INFO.IS_SPLIT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsSplit(Short isSplit) {
        this.isSplit = isSplit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PNR_INFO.RT_RESULT
     *
     * @return the value of UNIORDER.AIR_PNR_INFO.RT_RESULT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRtResult() {
        return rtResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PNR_INFO.RT_RESULT
     *
     * @param rtResult the value for UNIORDER.AIR_PNR_INFO.RT_RESULT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRtResult(String rtResult) {
        this.rtResult = rtResult;
    }
}