package com.wxfeng.mybatis.uniorder;

import java.math.BigDecimal;
import java.util.Date;

public class AirPaxSeg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.PAX_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long paxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.DEPART_AIRPORT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String departAirport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ARRIVE_AIRPORT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String arriveAirport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.DEPART_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date departDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ARRIVE_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date arriveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.SEG_INDEX
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short segIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.SEG_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String segType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.MARKET_CARRIER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String marketCarrier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.MARKET_FLT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String marketFltNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.IS_SHARE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.OPER_CARRIER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String operCarrier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.OPER_FLT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String operFltNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.CABIN_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String cabinCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.CABIN_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String cabinLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.SALE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal saleAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal payAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.FARE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal fareAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.AIRPORT_TAX
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal airportTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.FUEL_TAX
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal fuelTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal agencyFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ADD_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal addAgencyAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal agencyAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ADD_AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal addAgencyFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.FARE_BASIS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fareBasis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.TOUR_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String tourCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.EI
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String ei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.EI_COMMENT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String eiComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.RULE_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.DEPART_TERM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String departTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ARRIVE_TERM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String arriveTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.IS_VIA
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isVia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.VIA_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String viaInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.IS_MEAL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isMeal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.IS_ASR
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isAsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.PNR_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long pnrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long airOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.TKT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long tktId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String tktNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.TKT_SEG_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String tktSegStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.REL_PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String relPnrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.IS_HISTROY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isHistroy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.REL_SEG_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long relSegId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.SHOPPING_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String shoppingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.CHANGE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal changeAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.UPGRADE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal upgradeAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.CHANGE_TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal changeTaxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.CHANGE_PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String changePayType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.CHANGE_COUNT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short changeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.GIFT_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long giftPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ASR_RESULT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String asrResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.MEAL_RESULT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String mealResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String crtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String optId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date optDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.REFUND_APP_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long refundAppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.VALIDITYPERIOD
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String validityperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.MINSTAY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String minstay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.BAG_WEIGHT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String bagWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.DISCOUNT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.Y_CABIN_PRICE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal yCabinPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO_HISTORY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long airOrderNoHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ORDER_NO_HISTORY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long orderNoHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.AIR_PLANE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String airPlane;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.COUPON_NUMBER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal couponNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.DISCOUNT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal discountAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.DISCOUNT_RATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal discountRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ROUTING_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short routingNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.WUH_SMS_FLAG
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short wuhSmsFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.MEMBER_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String memberLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.MEAL_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String mealCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.NEST_STOCK_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String nestStockNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ORI_PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal oriPayAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.BASE_CABIN_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String baseCabinCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.COUPON_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String couponNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.COUPON_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String couponType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.FIX_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal fixAgencyAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.ORI_CABIN_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String oriCabinCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.PRODUCT_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_SEG.IS_KSEAT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isKseat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ID
     *
     * @param id the value for UNIORDER.AIR_PAX_SEG.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.PAX_ID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.PAX_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getPaxId() {
        return paxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.PAX_ID
     *
     * @param paxId the value for UNIORDER.AIR_PAX_SEG.PAX_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxId(Long paxId) {
        this.paxId = paxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.DEPART_AIRPORT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.DEPART_AIRPORT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getDepartAirport() {
        return departAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.DEPART_AIRPORT
     *
     * @param departAirport the value for UNIORDER.AIR_PAX_SEG.DEPART_AIRPORT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDepartAirport(String departAirport) {
        this.departAirport = departAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ARRIVE_AIRPORT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ARRIVE_AIRPORT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getArriveAirport() {
        return arriveAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ARRIVE_AIRPORT
     *
     * @param arriveAirport the value for UNIORDER.AIR_PAX_SEG.ARRIVE_AIRPORT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setArriveAirport(String arriveAirport) {
        this.arriveAirport = arriveAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.DEPART_DATE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.DEPART_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getDepartDate() {
        return departDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.DEPART_DATE
     *
     * @param departDate the value for UNIORDER.AIR_PAX_SEG.DEPART_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDepartDate(Date departDate) {
        this.departDate = departDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ARRIVE_DATE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ARRIVE_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getArriveDate() {
        return arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ARRIVE_DATE
     *
     * @param arriveDate the value for UNIORDER.AIR_PAX_SEG.ARRIVE_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setArriveDate(Date arriveDate) {
        this.arriveDate = arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.SEG_INDEX
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.SEG_INDEX
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getSegIndex() {
        return segIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.SEG_INDEX
     *
     * @param segIndex the value for UNIORDER.AIR_PAX_SEG.SEG_INDEX
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSegIndex(Short segIndex) {
        this.segIndex = segIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.SEG_TYPE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.SEG_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSegType() {
        return segType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.SEG_TYPE
     *
     * @param segType the value for UNIORDER.AIR_PAX_SEG.SEG_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSegType(String segType) {
        this.segType = segType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.MARKET_CARRIER
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.MARKET_CARRIER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getMarketCarrier() {
        return marketCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.MARKET_CARRIER
     *
     * @param marketCarrier the value for UNIORDER.AIR_PAX_SEG.MARKET_CARRIER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setMarketCarrier(String marketCarrier) {
        this.marketCarrier = marketCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.MARKET_FLT_NO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.MARKET_FLT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getMarketFltNo() {
        return marketFltNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.MARKET_FLT_NO
     *
     * @param marketFltNo the value for UNIORDER.AIR_PAX_SEG.MARKET_FLT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setMarketFltNo(String marketFltNo) {
        this.marketFltNo = marketFltNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.IS_SHARE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.IS_SHARE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.IS_SHARE
     *
     * @param isShare the value for UNIORDER.AIR_PAX_SEG.IS_SHARE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsShare(Short isShare) {
        this.isShare = isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.OPER_CARRIER
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.OPER_CARRIER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOperCarrier() {
        return operCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.OPER_CARRIER
     *
     * @param operCarrier the value for UNIORDER.AIR_PAX_SEG.OPER_CARRIER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOperCarrier(String operCarrier) {
        this.operCarrier = operCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.OPER_FLT_NO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.OPER_FLT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOperFltNo() {
        return operFltNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.OPER_FLT_NO
     *
     * @param operFltNo the value for UNIORDER.AIR_PAX_SEG.OPER_FLT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOperFltNo(String operFltNo) {
        this.operFltNo = operFltNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.CABIN_CODE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.CABIN_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCabinCode() {
        return cabinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.CABIN_CODE
     *
     * @param cabinCode the value for UNIORDER.AIR_PAX_SEG.CABIN_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCabinCode(String cabinCode) {
        this.cabinCode = cabinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.CABIN_LEVEL
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.CABIN_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCabinLevel() {
        return cabinLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.CABIN_LEVEL
     *
     * @param cabinLevel the value for UNIORDER.AIR_PAX_SEG.CABIN_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCabinLevel(String cabinLevel) {
        this.cabinLevel = cabinLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.SALE_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.SALE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getSaleAmt() {
        return saleAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.SALE_AMT
     *
     * @param saleAmt the value for UNIORDER.AIR_PAX_SEG.SALE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSaleAmt(BigDecimal saleAmt) {
        this.saleAmt = saleAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.PAY_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getPayAmt() {
        return payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.PAY_AMT
     *
     * @param payAmt the value for UNIORDER.AIR_PAX_SEG.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayAmt(BigDecimal payAmt) {
        this.payAmt = payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.FARE_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.FARE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getFareAmt() {
        return fareAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.FARE_AMT
     *
     * @param fareAmt the value for UNIORDER.AIR_PAX_SEG.FARE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFareAmt(BigDecimal fareAmt) {
        this.fareAmt = fareAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.AIRPORT_TAX
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.AIRPORT_TAX
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAirportTax() {
        return airportTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.AIRPORT_TAX
     *
     * @param airportTax the value for UNIORDER.AIR_PAX_SEG.AIRPORT_TAX
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirportTax(BigDecimal airportTax) {
        this.airportTax = airportTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.FUEL_TAX
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.FUEL_TAX
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getFuelTax() {
        return fuelTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.FUEL_TAX
     *
     * @param fuelTax the value for UNIORDER.AIR_PAX_SEG.FUEL_TAX
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFuelTax(BigDecimal fuelTax) {
        this.fuelTax = fuelTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.AGENCY_FEE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAgencyFee() {
        return agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.AGENCY_FEE
     *
     * @param agencyFee the value for UNIORDER.AIR_PAX_SEG.AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAgencyFee(BigDecimal agencyFee) {
        this.agencyFee = agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ADD_AGENCY_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ADD_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAddAgencyAmt() {
        return addAgencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ADD_AGENCY_AMT
     *
     * @param addAgencyAmt the value for UNIORDER.AIR_PAX_SEG.ADD_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAddAgencyAmt(BigDecimal addAgencyAmt) {
        this.addAgencyAmt = addAgencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.AGENCY_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAgencyAmt() {
        return agencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.AGENCY_AMT
     *
     * @param agencyAmt the value for UNIORDER.AIR_PAX_SEG.AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAgencyAmt(BigDecimal agencyAmt) {
        this.agencyAmt = agencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ADD_AGENCY_FEE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ADD_AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAddAgencyFee() {
        return addAgencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ADD_AGENCY_FEE
     *
     * @param addAgencyFee the value for UNIORDER.AIR_PAX_SEG.ADD_AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAddAgencyFee(BigDecimal addAgencyFee) {
        this.addAgencyFee = addAgencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.PAY_TYPE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.PAY_TYPE
     *
     * @param payType the value for UNIORDER.AIR_PAX_SEG.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.FARE_BASIS
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.FARE_BASIS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFareBasis() {
        return fareBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.FARE_BASIS
     *
     * @param fareBasis the value for UNIORDER.AIR_PAX_SEG.FARE_BASIS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFareBasis(String fareBasis) {
        this.fareBasis = fareBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.TOUR_CODE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.TOUR_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getTourCode() {
        return tourCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.TOUR_CODE
     *
     * @param tourCode the value for UNIORDER.AIR_PAX_SEG.TOUR_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTourCode(String tourCode) {
        this.tourCode = tourCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.EI
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.EI
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getEi() {
        return ei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.EI
     *
     * @param ei the value for UNIORDER.AIR_PAX_SEG.EI
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setEi(String ei) {
        this.ei = ei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.EI_COMMENT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.EI_COMMENT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getEiComment() {
        return eiComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.EI_COMMENT
     *
     * @param eiComment the value for UNIORDER.AIR_PAX_SEG.EI_COMMENT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setEiComment(String eiComment) {
        this.eiComment = eiComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.RULE_ID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.RULE_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.RULE_ID
     *
     * @param ruleId the value for UNIORDER.AIR_PAX_SEG.RULE_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.DEPART_TERM
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.DEPART_TERM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getDepartTerm() {
        return departTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.DEPART_TERM
     *
     * @param departTerm the value for UNIORDER.AIR_PAX_SEG.DEPART_TERM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDepartTerm(String departTerm) {
        this.departTerm = departTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ARRIVE_TERM
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ARRIVE_TERM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getArriveTerm() {
        return arriveTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ARRIVE_TERM
     *
     * @param arriveTerm the value for UNIORDER.AIR_PAX_SEG.ARRIVE_TERM
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setArriveTerm(String arriveTerm) {
        this.arriveTerm = arriveTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.IS_VIA
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.IS_VIA
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsVia() {
        return isVia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.IS_VIA
     *
     * @param isVia the value for UNIORDER.AIR_PAX_SEG.IS_VIA
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsVia(Short isVia) {
        this.isVia = isVia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.VIA_INFO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.VIA_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getViaInfo() {
        return viaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.VIA_INFO
     *
     * @param viaInfo the value for UNIORDER.AIR_PAX_SEG.VIA_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setViaInfo(String viaInfo) {
        this.viaInfo = viaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.IS_MEAL
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.IS_MEAL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsMeal() {
        return isMeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.IS_MEAL
     *
     * @param isMeal the value for UNIORDER.AIR_PAX_SEG.IS_MEAL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsMeal(Short isMeal) {
        this.isMeal = isMeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.IS_ASR
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.IS_ASR
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsAsr() {
        return isAsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.IS_ASR
     *
     * @param isAsr the value for UNIORDER.AIR_PAX_SEG.IS_ASR
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsAsr(Short isAsr) {
        this.isAsr = isAsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.PNR_ID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.PNR_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getPnrId() {
        return pnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.PNR_ID
     *
     * @param pnrId the value for UNIORDER.AIR_PAX_SEG.PNR_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPnrId(Long pnrId) {
        this.pnrId = pnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getAirOrderNo() {
        return airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO
     *
     * @param airOrderNo the value for UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirOrderNo(Long airOrderNo) {
        this.airOrderNo = airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ORDER_NO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ORDER_NO
     *
     * @param orderNo the value for UNIORDER.AIR_PAX_SEG.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.TKT_ID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.TKT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getTktId() {
        return tktId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.TKT_ID
     *
     * @param tktId the value for UNIORDER.AIR_PAX_SEG.TKT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTktId(Long tktId) {
        this.tktId = tktId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.TKT_NO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getTktNo() {
        return tktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.TKT_NO
     *
     * @param tktNo the value for UNIORDER.AIR_PAX_SEG.TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTktNo(String tktNo) {
        this.tktNo = tktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.TKT_SEG_STATUS
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.TKT_SEG_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getTktSegStatus() {
        return tktSegStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.TKT_SEG_STATUS
     *
     * @param tktSegStatus the value for UNIORDER.AIR_PAX_SEG.TKT_SEG_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTktSegStatus(String tktSegStatus) {
        this.tktSegStatus = tktSegStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.REL_PNR_NO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.REL_PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRelPnrNo() {
        return relPnrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.REL_PNR_NO
     *
     * @param relPnrNo the value for UNIORDER.AIR_PAX_SEG.REL_PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRelPnrNo(String relPnrNo) {
        this.relPnrNo = relPnrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.IS_HISTROY
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.IS_HISTROY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsHistroy() {
        return isHistroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.IS_HISTROY
     *
     * @param isHistroy the value for UNIORDER.AIR_PAX_SEG.IS_HISTROY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsHistroy(Short isHistroy) {
        this.isHistroy = isHistroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.REL_SEG_ID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.REL_SEG_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getRelSegId() {
        return relSegId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.REL_SEG_ID
     *
     * @param relSegId the value for UNIORDER.AIR_PAX_SEG.REL_SEG_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRelSegId(Long relSegId) {
        this.relSegId = relSegId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.SHOPPING_TYPE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.SHOPPING_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getShoppingType() {
        return shoppingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.SHOPPING_TYPE
     *
     * @param shoppingType the value for UNIORDER.AIR_PAX_SEG.SHOPPING_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setShoppingType(String shoppingType) {
        this.shoppingType = shoppingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.CHANGE_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.CHANGE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getChangeAmt() {
        return changeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.CHANGE_AMT
     *
     * @param changeAmt the value for UNIORDER.AIR_PAX_SEG.CHANGE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChangeAmt(BigDecimal changeAmt) {
        this.changeAmt = changeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.UPGRADE_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.UPGRADE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getUpgradeAmt() {
        return upgradeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.UPGRADE_AMT
     *
     * @param upgradeAmt the value for UNIORDER.AIR_PAX_SEG.UPGRADE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setUpgradeAmt(BigDecimal upgradeAmt) {
        this.upgradeAmt = upgradeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.CHANGE_TAX_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.CHANGE_TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getChangeTaxAmt() {
        return changeTaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.CHANGE_TAX_AMT
     *
     * @param changeTaxAmt the value for UNIORDER.AIR_PAX_SEG.CHANGE_TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChangeTaxAmt(BigDecimal changeTaxAmt) {
        this.changeTaxAmt = changeTaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.CHANGE_PAY_TYPE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.CHANGE_PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getChangePayType() {
        return changePayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.CHANGE_PAY_TYPE
     *
     * @param changePayType the value for UNIORDER.AIR_PAX_SEG.CHANGE_PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChangePayType(String changePayType) {
        this.changePayType = changePayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.CHANGE_COUNT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.CHANGE_COUNT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getChangeCount() {
        return changeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.CHANGE_COUNT
     *
     * @param changeCount the value for UNIORDER.AIR_PAX_SEG.CHANGE_COUNT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChangeCount(Short changeCount) {
        this.changeCount = changeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.GIFT_POINT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.GIFT_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getGiftPoint() {
        return giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.GIFT_POINT
     *
     * @param giftPoint the value for UNIORDER.AIR_PAX_SEG.GIFT_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setGiftPoint(Long giftPoint) {
        this.giftPoint = giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ASR_RESULT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ASR_RESULT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getAsrResult() {
        return asrResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ASR_RESULT
     *
     * @param asrResult the value for UNIORDER.AIR_PAX_SEG.ASR_RESULT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAsrResult(String asrResult) {
        this.asrResult = asrResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.MEAL_RESULT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.MEAL_RESULT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getMealResult() {
        return mealResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.MEAL_RESULT
     *
     * @param mealResult the value for UNIORDER.AIR_PAX_SEG.MEAL_RESULT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setMealResult(String mealResult) {
        this.mealResult = mealResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.REMARK
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.REMARK
     *
     * @param remark the value for UNIORDER.AIR_PAX_SEG.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.IS_VALID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.IS_VALID
     *
     * @param isValid the value for UNIORDER.AIR_PAX_SEG.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsValid(Short isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.CRT_ID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCrtId() {
        return crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.CRT_ID
     *
     * @param crtId the value for UNIORDER.AIR_PAX_SEG.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.CRT_DT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.CRT_DT
     *
     * @param crtDt the value for UNIORDER.AIR_PAX_SEG.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtDt(Date crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.OPT_ID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.OPT_ID
     *
     * @param optId the value for UNIORDER.AIR_PAX_SEG.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptId(String optId) {
        this.optId = optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.OPT_DT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getOptDt() {
        return optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.OPT_DT
     *
     * @param optDt the value for UNIORDER.AIR_PAX_SEG.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptDt(Date optDt) {
        this.optDt = optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.VERSION
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.VERSION
     *
     * @param version the value for UNIORDER.AIR_PAX_SEG.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.REFUND_APP_ID
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.REFUND_APP_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getRefundAppId() {
        return refundAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.REFUND_APP_ID
     *
     * @param refundAppId the value for UNIORDER.AIR_PAX_SEG.REFUND_APP_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRefundAppId(Long refundAppId) {
        this.refundAppId = refundAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.VALIDITYPERIOD
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.VALIDITYPERIOD
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getValidityperiod() {
        return validityperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.VALIDITYPERIOD
     *
     * @param validityperiod the value for UNIORDER.AIR_PAX_SEG.VALIDITYPERIOD
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setValidityperiod(String validityperiod) {
        this.validityperiod = validityperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.MINSTAY
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.MINSTAY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getMinstay() {
        return minstay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.MINSTAY
     *
     * @param minstay the value for UNIORDER.AIR_PAX_SEG.MINSTAY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setMinstay(String minstay) {
        this.minstay = minstay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.BAG_WEIGHT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.BAG_WEIGHT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getBagWeight() {
        return bagWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.BAG_WEIGHT
     *
     * @param bagWeight the value for UNIORDER.AIR_PAX_SEG.BAG_WEIGHT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setBagWeight(String bagWeight) {
        this.bagWeight = bagWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.DISCOUNT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.DISCOUNT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.DISCOUNT
     *
     * @param discount the value for UNIORDER.AIR_PAX_SEG.DISCOUNT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.Y_CABIN_PRICE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.Y_CABIN_PRICE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getyCabinPrice() {
        return yCabinPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.Y_CABIN_PRICE
     *
     * @param yCabinPrice the value for UNIORDER.AIR_PAX_SEG.Y_CABIN_PRICE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setyCabinPrice(BigDecimal yCabinPrice) {
        this.yCabinPrice = yCabinPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO_HISTORY
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO_HISTORY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getAirOrderNoHistory() {
        return airOrderNoHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO_HISTORY
     *
     * @param airOrderNoHistory the value for UNIORDER.AIR_PAX_SEG.AIR_ORDER_NO_HISTORY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirOrderNoHistory(Long airOrderNoHistory) {
        this.airOrderNoHistory = airOrderNoHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ORDER_NO_HISTORY
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ORDER_NO_HISTORY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getOrderNoHistory() {
        return orderNoHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ORDER_NO_HISTORY
     *
     * @param orderNoHistory the value for UNIORDER.AIR_PAX_SEG.ORDER_NO_HISTORY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderNoHistory(Long orderNoHistory) {
        this.orderNoHistory = orderNoHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.AIR_PLANE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.AIR_PLANE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getAirPlane() {
        return airPlane;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.AIR_PLANE
     *
     * @param airPlane the value for UNIORDER.AIR_PAX_SEG.AIR_PLANE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirPlane(String airPlane) {
        this.airPlane = airPlane;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.COUPON_NUMBER
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.COUPON_NUMBER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getCouponNumber() {
        return couponNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.COUPON_NUMBER
     *
     * @param couponNumber the value for UNIORDER.AIR_PAX_SEG.COUPON_NUMBER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCouponNumber(BigDecimal couponNumber) {
        this.couponNumber = couponNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.DISCOUNT_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.DISCOUNT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getDiscountAmt() {
        return discountAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.DISCOUNT_AMT
     *
     * @param discountAmt the value for UNIORDER.AIR_PAX_SEG.DISCOUNT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDiscountAmt(BigDecimal discountAmt) {
        this.discountAmt = discountAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.DISCOUNT_RATE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.DISCOUNT_RATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.DISCOUNT_RATE
     *
     * @param discountRate the value for UNIORDER.AIR_PAX_SEG.DISCOUNT_RATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDiscountRate(BigDecimal discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ROUTING_NO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ROUTING_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getRoutingNo() {
        return routingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ROUTING_NO
     *
     * @param routingNo the value for UNIORDER.AIR_PAX_SEG.ROUTING_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRoutingNo(Short routingNo) {
        this.routingNo = routingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.WUH_SMS_FLAG
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.WUH_SMS_FLAG
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getWuhSmsFlag() {
        return wuhSmsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.WUH_SMS_FLAG
     *
     * @param wuhSmsFlag the value for UNIORDER.AIR_PAX_SEG.WUH_SMS_FLAG
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setWuhSmsFlag(Short wuhSmsFlag) {
        this.wuhSmsFlag = wuhSmsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.MEMBER_LEVEL
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.MEMBER_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getMemberLevel() {
        return memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.MEMBER_LEVEL
     *
     * @param memberLevel the value for UNIORDER.AIR_PAX_SEG.MEMBER_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setMemberLevel(String memberLevel) {
        this.memberLevel = memberLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.MEAL_CODE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.MEAL_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getMealCode() {
        return mealCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.MEAL_CODE
     *
     * @param mealCode the value for UNIORDER.AIR_PAX_SEG.MEAL_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setMealCode(String mealCode) {
        this.mealCode = mealCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.NEST_STOCK_NO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.NEST_STOCK_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getNestStockNo() {
        return nestStockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.NEST_STOCK_NO
     *
     * @param nestStockNo the value for UNIORDER.AIR_PAX_SEG.NEST_STOCK_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setNestStockNo(String nestStockNo) {
        this.nestStockNo = nestStockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ORI_PAY_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ORI_PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getOriPayAmt() {
        return oriPayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ORI_PAY_AMT
     *
     * @param oriPayAmt the value for UNIORDER.AIR_PAX_SEG.ORI_PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOriPayAmt(BigDecimal oriPayAmt) {
        this.oriPayAmt = oriPayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.BASE_CABIN_CODE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.BASE_CABIN_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getBaseCabinCode() {
        return baseCabinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.BASE_CABIN_CODE
     *
     * @param baseCabinCode the value for UNIORDER.AIR_PAX_SEG.BASE_CABIN_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setBaseCabinCode(String baseCabinCode) {
        this.baseCabinCode = baseCabinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.COUPON_NO
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.COUPON_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCouponNo() {
        return couponNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.COUPON_NO
     *
     * @param couponNo the value for UNIORDER.AIR_PAX_SEG.COUPON_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCouponNo(String couponNo) {
        this.couponNo = couponNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.COUPON_TYPE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.COUPON_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.COUPON_TYPE
     *
     * @param couponType the value for UNIORDER.AIR_PAX_SEG.COUPON_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCouponType(String couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.FIX_AGENCY_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.FIX_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getFixAgencyAmt() {
        return fixAgencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.FIX_AGENCY_AMT
     *
     * @param fixAgencyAmt the value for UNIORDER.AIR_PAX_SEG.FIX_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFixAgencyAmt(BigDecimal fixAgencyAmt) {
        this.fixAgencyAmt = fixAgencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.ORI_CABIN_CODE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.ORI_CABIN_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOriCabinCode() {
        return oriCabinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.ORI_CABIN_CODE
     *
     * @param oriCabinCode the value for UNIORDER.AIR_PAX_SEG.ORI_CABIN_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOriCabinCode(String oriCabinCode) {
        this.oriCabinCode = oriCabinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.PRODUCT_CODE
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.PRODUCT_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.PRODUCT_CODE
     *
     * @param productCode the value for UNIORDER.AIR_PAX_SEG.PRODUCT_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_SEG.IS_KSEAT
     *
     * @return the value of UNIORDER.AIR_PAX_SEG.IS_KSEAT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsKseat() {
        return isKseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_SEG.IS_KSEAT
     *
     * @param isKseat the value for UNIORDER.AIR_PAX_SEG.IS_KSEAT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsKseat(Short isKseat) {
        this.isKseat = isKseat;
    }
}