package com.wxfeng.mybatis.uniorder;

import java.math.BigDecimal;
import java.util.Date;

public class AirPaxInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.PAX_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String paxName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.PAX_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String paxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.PAX_NAME_PY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String paxNamePy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.PAX_NAME_LAST
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String paxNameLast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.PAX_NAME_FIRST
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String paxNameFirst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.INF_CARRIER_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long infCarrierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.INF_CARRIER_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String infCarrierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.BIRTHDAY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.GENDER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.APPELLATION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String appellation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.NATIONALITY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.ID_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String idType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.ID_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String idNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.ID_VALID_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date idValidDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.ID_ISSUE_NATION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String idIssueNation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.FFP_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String ffpNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.FFP_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String ffpLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.PNR_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long pnrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long airOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.IS_PACKAGE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isPackage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.SALE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal saleAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal payAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.POINT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long pointAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal taxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal agencyFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.ADD_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal addAgencyAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal agencyAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.ADD_AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal addAgencyFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.RULE_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.DOCA_STATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String docaState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.DOCA_STREET
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String docaStreet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.DOCA_CITY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String docaCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.DOCA_POST_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String docaPostCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.MOBILE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.EMAIL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String crtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String optId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date optDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.DOCA_NATION_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String docaNationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.FARE_RULE_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fareRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.GIFT_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal giftPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short channelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.FIX_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal fixAgencyAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_PAX_INFO.PHONE_NUMBER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String phoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.ID
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.ID
     *
     * @param id the value for UNIORDER.AIR_PAX_INFO.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.PAX_NAME
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.PAX_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPaxName() {
        return paxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.PAX_NAME
     *
     * @param paxName the value for UNIORDER.AIR_PAX_INFO.PAX_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxName(String paxName) {
        this.paxName = paxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.PAX_TYPE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.PAX_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPaxType() {
        return paxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.PAX_TYPE
     *
     * @param paxType the value for UNIORDER.AIR_PAX_INFO.PAX_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxType(String paxType) {
        this.paxType = paxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.PAX_NAME_PY
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.PAX_NAME_PY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPaxNamePy() {
        return paxNamePy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.PAX_NAME_PY
     *
     * @param paxNamePy the value for UNIORDER.AIR_PAX_INFO.PAX_NAME_PY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxNamePy(String paxNamePy) {
        this.paxNamePy = paxNamePy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.PAX_NAME_LAST
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.PAX_NAME_LAST
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPaxNameLast() {
        return paxNameLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.PAX_NAME_LAST
     *
     * @param paxNameLast the value for UNIORDER.AIR_PAX_INFO.PAX_NAME_LAST
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxNameLast(String paxNameLast) {
        this.paxNameLast = paxNameLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.PAX_NAME_FIRST
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.PAX_NAME_FIRST
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPaxNameFirst() {
        return paxNameFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.PAX_NAME_FIRST
     *
     * @param paxNameFirst the value for UNIORDER.AIR_PAX_INFO.PAX_NAME_FIRST
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxNameFirst(String paxNameFirst) {
        this.paxNameFirst = paxNameFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.INF_CARRIER_ID
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.INF_CARRIER_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getInfCarrierId() {
        return infCarrierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.INF_CARRIER_ID
     *
     * @param infCarrierId the value for UNIORDER.AIR_PAX_INFO.INF_CARRIER_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setInfCarrierId(Long infCarrierId) {
        this.infCarrierId = infCarrierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.INF_CARRIER_NAME
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.INF_CARRIER_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getInfCarrierName() {
        return infCarrierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.INF_CARRIER_NAME
     *
     * @param infCarrierName the value for UNIORDER.AIR_PAX_INFO.INF_CARRIER_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setInfCarrierName(String infCarrierName) {
        this.infCarrierName = infCarrierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.BIRTHDAY
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.BIRTHDAY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.BIRTHDAY
     *
     * @param birthday the value for UNIORDER.AIR_PAX_INFO.BIRTHDAY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.GENDER
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.GENDER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.GENDER
     *
     * @param gender the value for UNIORDER.AIR_PAX_INFO.GENDER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.APPELLATION
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.APPELLATION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getAppellation() {
        return appellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.APPELLATION
     *
     * @param appellation the value for UNIORDER.AIR_PAX_INFO.APPELLATION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAppellation(String appellation) {
        this.appellation = appellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.NATIONALITY
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.NATIONALITY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.NATIONALITY
     *
     * @param nationality the value for UNIORDER.AIR_PAX_INFO.NATIONALITY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.ID_TYPE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.ID_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.ID_TYPE
     *
     * @param idType the value for UNIORDER.AIR_PAX_INFO.ID_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIdType(String idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.ID_NO
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.ID_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.ID_NO
     *
     * @param idNo the value for UNIORDER.AIR_PAX_INFO.ID_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.ID_VALID_DT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.ID_VALID_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getIdValidDt() {
        return idValidDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.ID_VALID_DT
     *
     * @param idValidDt the value for UNIORDER.AIR_PAX_INFO.ID_VALID_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIdValidDt(Date idValidDt) {
        this.idValidDt = idValidDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.ID_ISSUE_NATION
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.ID_ISSUE_NATION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getIdIssueNation() {
        return idIssueNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.ID_ISSUE_NATION
     *
     * @param idIssueNation the value for UNIORDER.AIR_PAX_INFO.ID_ISSUE_NATION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIdIssueNation(String idIssueNation) {
        this.idIssueNation = idIssueNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.FFP_NO
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.FFP_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFfpNo() {
        return ffpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.FFP_NO
     *
     * @param ffpNo the value for UNIORDER.AIR_PAX_INFO.FFP_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFfpNo(String ffpNo) {
        this.ffpNo = ffpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.FFP_LEVEL
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.FFP_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFfpLevel() {
        return ffpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.FFP_LEVEL
     *
     * @param ffpLevel the value for UNIORDER.AIR_PAX_INFO.FFP_LEVEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFfpLevel(String ffpLevel) {
        this.ffpLevel = ffpLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.PNR_ID
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.PNR_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getPnrId() {
        return pnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.PNR_ID
     *
     * @param pnrId the value for UNIORDER.AIR_PAX_INFO.PNR_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPnrId(Long pnrId) {
        this.pnrId = pnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.AIR_ORDER_NO
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getAirOrderNo() {
        return airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.AIR_ORDER_NO
     *
     * @param airOrderNo the value for UNIORDER.AIR_PAX_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirOrderNo(Long airOrderNo) {
        this.airOrderNo = airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.ORDER_NO
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.ORDER_NO
     *
     * @param orderNo the value for UNIORDER.AIR_PAX_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.IS_PACKAGE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.IS_PACKAGE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsPackage() {
        return isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.IS_PACKAGE
     *
     * @param isPackage the value for UNIORDER.AIR_PAX_INFO.IS_PACKAGE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsPackage(Short isPackage) {
        this.isPackage = isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.SALE_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.SALE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getSaleAmt() {
        return saleAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.SALE_AMT
     *
     * @param saleAmt the value for UNIORDER.AIR_PAX_INFO.SALE_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSaleAmt(BigDecimal saleAmt) {
        this.saleAmt = saleAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.PAY_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getPayAmt() {
        return payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.PAY_AMT
     *
     * @param payAmt the value for UNIORDER.AIR_PAX_INFO.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayAmt(BigDecimal payAmt) {
        this.payAmt = payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.POINT_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.POINT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getPointAmt() {
        return pointAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.POINT_AMT
     *
     * @param pointAmt the value for UNIORDER.AIR_PAX_INFO.POINT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPointAmt(Long pointAmt) {
        this.pointAmt = pointAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.TAX_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getTaxAmt() {
        return taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.TAX_AMT
     *
     * @param taxAmt the value for UNIORDER.AIR_PAX_INFO.TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTaxAmt(BigDecimal taxAmt) {
        this.taxAmt = taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.AGENCY_FEE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAgencyFee() {
        return agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.AGENCY_FEE
     *
     * @param agencyFee the value for UNIORDER.AIR_PAX_INFO.AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAgencyFee(BigDecimal agencyFee) {
        this.agencyFee = agencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.ADD_AGENCY_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.ADD_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAddAgencyAmt() {
        return addAgencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.ADD_AGENCY_AMT
     *
     * @param addAgencyAmt the value for UNIORDER.AIR_PAX_INFO.ADD_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAddAgencyAmt(BigDecimal addAgencyAmt) {
        this.addAgencyAmt = addAgencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.AGENCY_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAgencyAmt() {
        return agencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.AGENCY_AMT
     *
     * @param agencyAmt the value for UNIORDER.AIR_PAX_INFO.AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAgencyAmt(BigDecimal agencyAmt) {
        this.agencyAmt = agencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.ADD_AGENCY_FEE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.ADD_AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getAddAgencyFee() {
        return addAgencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.ADD_AGENCY_FEE
     *
     * @param addAgencyFee the value for UNIORDER.AIR_PAX_INFO.ADD_AGENCY_FEE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAddAgencyFee(BigDecimal addAgencyFee) {
        this.addAgencyFee = addAgencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.PAY_TYPE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.PAY_TYPE
     *
     * @param payType the value for UNIORDER.AIR_PAX_INFO.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.RULE_ID
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.RULE_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.RULE_ID
     *
     * @param ruleId the value for UNIORDER.AIR_PAX_INFO.RULE_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_STATE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.DOCA_STATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getDocaState() {
        return docaState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_STATE
     *
     * @param docaState the value for UNIORDER.AIR_PAX_INFO.DOCA_STATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDocaState(String docaState) {
        this.docaState = docaState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_STREET
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.DOCA_STREET
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getDocaStreet() {
        return docaStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_STREET
     *
     * @param docaStreet the value for UNIORDER.AIR_PAX_INFO.DOCA_STREET
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDocaStreet(String docaStreet) {
        this.docaStreet = docaStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_CITY
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.DOCA_CITY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getDocaCity() {
        return docaCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_CITY
     *
     * @param docaCity the value for UNIORDER.AIR_PAX_INFO.DOCA_CITY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDocaCity(String docaCity) {
        this.docaCity = docaCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_POST_CODE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.DOCA_POST_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getDocaPostCode() {
        return docaPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_POST_CODE
     *
     * @param docaPostCode the value for UNIORDER.AIR_PAX_INFO.DOCA_POST_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDocaPostCode(String docaPostCode) {
        this.docaPostCode = docaPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.MOBILE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.MOBILE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.MOBILE
     *
     * @param mobile the value for UNIORDER.AIR_PAX_INFO.MOBILE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.EMAIL
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.EMAIL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.EMAIL
     *
     * @param email the value for UNIORDER.AIR_PAX_INFO.EMAIL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.REMARK
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.REMARK
     *
     * @param remark the value for UNIORDER.AIR_PAX_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.IS_VALID
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.IS_VALID
     *
     * @param isValid the value for UNIORDER.AIR_PAX_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsValid(Short isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.CRT_ID
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCrtId() {
        return crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.CRT_ID
     *
     * @param crtId the value for UNIORDER.AIR_PAX_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.CRT_DT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.CRT_DT
     *
     * @param crtDt the value for UNIORDER.AIR_PAX_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtDt(Date crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.OPT_ID
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.OPT_ID
     *
     * @param optId the value for UNIORDER.AIR_PAX_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptId(String optId) {
        this.optId = optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.OPT_DT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getOptDt() {
        return optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.OPT_DT
     *
     * @param optDt the value for UNIORDER.AIR_PAX_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptDt(Date optDt) {
        this.optDt = optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.VERSION
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.VERSION
     *
     * @param version the value for UNIORDER.AIR_PAX_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_NATION_CODE
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.DOCA_NATION_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getDocaNationCode() {
        return docaNationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.DOCA_NATION_CODE
     *
     * @param docaNationCode the value for UNIORDER.AIR_PAX_INFO.DOCA_NATION_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDocaNationCode(String docaNationCode) {
        this.docaNationCode = docaNationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.FARE_RULE_ID
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.FARE_RULE_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFareRuleId() {
        return fareRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.FARE_RULE_ID
     *
     * @param fareRuleId the value for UNIORDER.AIR_PAX_INFO.FARE_RULE_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFareRuleId(String fareRuleId) {
        this.fareRuleId = fareRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.GIFT_POINT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.GIFT_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getGiftPoint() {
        return giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.GIFT_POINT
     *
     * @param giftPoint the value for UNIORDER.AIR_PAX_INFO.GIFT_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setGiftPoint(BigDecimal giftPoint) {
        this.giftPoint = giftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.CHANNEL_NO
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.CHANNEL_NO
     *
     * @param channelNo the value for UNIORDER.AIR_PAX_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChannelNo(Short channelNo) {
        this.channelNo = channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.FIX_AGENCY_AMT
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.FIX_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getFixAgencyAmt() {
        return fixAgencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.FIX_AGENCY_AMT
     *
     * @param fixAgencyAmt the value for UNIORDER.AIR_PAX_INFO.FIX_AGENCY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFixAgencyAmt(BigDecimal fixAgencyAmt) {
        this.fixAgencyAmt = fixAgencyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_PAX_INFO.PHONE_NUMBER
     *
     * @return the value of UNIORDER.AIR_PAX_INFO.PHONE_NUMBER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_PAX_INFO.PHONE_NUMBER
     *
     * @param phoneNumber the value for UNIORDER.AIR_PAX_INFO.PHONE_NUMBER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}