package com.wxfeng.mybatis.uniorder;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AirTktInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public AirTktInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTktNoIsNull() {
            addCriterion("TKT_NO is null");
            return (Criteria) this;
        }

        public Criteria andTktNoIsNotNull() {
            addCriterion("TKT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTktNoEqualTo(String value) {
            addCriterion("TKT_NO =", value, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoNotEqualTo(String value) {
            addCriterion("TKT_NO <>", value, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoGreaterThan(String value) {
            addCriterion("TKT_NO >", value, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoGreaterThanOrEqualTo(String value) {
            addCriterion("TKT_NO >=", value, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoLessThan(String value) {
            addCriterion("TKT_NO <", value, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoLessThanOrEqualTo(String value) {
            addCriterion("TKT_NO <=", value, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoLike(String value) {
            addCriterion("TKT_NO like", value, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoNotLike(String value) {
            addCriterion("TKT_NO not like", value, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoIn(List<String> values) {
            addCriterion("TKT_NO in", values, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoNotIn(List<String> values) {
            addCriterion("TKT_NO not in", values, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoBetween(String value1, String value2) {
            addCriterion("TKT_NO between", value1, value2, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTktNoNotBetween(String value1, String value2) {
            addCriterion("TKT_NO not between", value1, value2, "tktNo");
            return (Criteria) this;
        }

        public Criteria andTripTypeIsNull() {
            addCriterion("TRIP_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTripTypeIsNotNull() {
            addCriterion("TRIP_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTripTypeEqualTo(String value) {
            addCriterion("TRIP_TYPE =", value, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeNotEqualTo(String value) {
            addCriterion("TRIP_TYPE <>", value, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeGreaterThan(String value) {
            addCriterion("TRIP_TYPE >", value, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TRIP_TYPE >=", value, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeLessThan(String value) {
            addCriterion("TRIP_TYPE <", value, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeLessThanOrEqualTo(String value) {
            addCriterion("TRIP_TYPE <=", value, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeLike(String value) {
            addCriterion("TRIP_TYPE like", value, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeNotLike(String value) {
            addCriterion("TRIP_TYPE not like", value, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeIn(List<String> values) {
            addCriterion("TRIP_TYPE in", values, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeNotIn(List<String> values) {
            addCriterion("TRIP_TYPE not in", values, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeBetween(String value1, String value2) {
            addCriterion("TRIP_TYPE between", value1, value2, "tripType");
            return (Criteria) this;
        }

        public Criteria andTripTypeNotBetween(String value1, String value2) {
            addCriterion("TRIP_TYPE not between", value1, value2, "tripType");
            return (Criteria) this;
        }

        public Criteria andIsPointIsNull() {
            addCriterion("IS_POINT is null");
            return (Criteria) this;
        }

        public Criteria andIsPointIsNotNull() {
            addCriterion("IS_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andIsPointEqualTo(Short value) {
            addCriterion("IS_POINT =", value, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsPointNotEqualTo(Short value) {
            addCriterion("IS_POINT <>", value, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsPointGreaterThan(Short value) {
            addCriterion("IS_POINT >", value, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsPointGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_POINT >=", value, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsPointLessThan(Short value) {
            addCriterion("IS_POINT <", value, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsPointLessThanOrEqualTo(Short value) {
            addCriterion("IS_POINT <=", value, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsPointIn(List<Short> values) {
            addCriterion("IS_POINT in", values, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsPointNotIn(List<Short> values) {
            addCriterion("IS_POINT not in", values, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsPointBetween(Short value1, Short value2) {
            addCriterion("IS_POINT between", value1, value2, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsPointNotBetween(Short value1, Short value2) {
            addCriterion("IS_POINT not between", value1, value2, "isPoint");
            return (Criteria) this;
        }

        public Criteria andIsExchangeIsNull() {
            addCriterion("IS_EXCHANGE is null");
            return (Criteria) this;
        }

        public Criteria andIsExchangeIsNotNull() {
            addCriterion("IS_EXCHANGE is not null");
            return (Criteria) this;
        }

        public Criteria andIsExchangeEqualTo(Short value) {
            addCriterion("IS_EXCHANGE =", value, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsExchangeNotEqualTo(Short value) {
            addCriterion("IS_EXCHANGE <>", value, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsExchangeGreaterThan(Short value) {
            addCriterion("IS_EXCHANGE >", value, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsExchangeGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_EXCHANGE >=", value, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsExchangeLessThan(Short value) {
            addCriterion("IS_EXCHANGE <", value, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsExchangeLessThanOrEqualTo(Short value) {
            addCriterion("IS_EXCHANGE <=", value, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsExchangeIn(List<Short> values) {
            addCriterion("IS_EXCHANGE in", values, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsExchangeNotIn(List<Short> values) {
            addCriterion("IS_EXCHANGE not in", values, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsExchangeBetween(Short value1, Short value2) {
            addCriterion("IS_EXCHANGE between", value1, value2, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsExchangeNotBetween(Short value1, Short value2) {
            addCriterion("IS_EXCHANGE not between", value1, value2, "isExchange");
            return (Criteria) this;
        }

        public Criteria andIsCancelIsNull() {
            addCriterion("IS_CANCEL is null");
            return (Criteria) this;
        }

        public Criteria andIsCancelIsNotNull() {
            addCriterion("IS_CANCEL is not null");
            return (Criteria) this;
        }

        public Criteria andIsCancelEqualTo(Short value) {
            addCriterion("IS_CANCEL =", value, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsCancelNotEqualTo(Short value) {
            addCriterion("IS_CANCEL <>", value, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsCancelGreaterThan(Short value) {
            addCriterion("IS_CANCEL >", value, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsCancelGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_CANCEL >=", value, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsCancelLessThan(Short value) {
            addCriterion("IS_CANCEL <", value, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsCancelLessThanOrEqualTo(Short value) {
            addCriterion("IS_CANCEL <=", value, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsCancelIn(List<Short> values) {
            addCriterion("IS_CANCEL in", values, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsCancelNotIn(List<Short> values) {
            addCriterion("IS_CANCEL not in", values, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsCancelBetween(Short value1, Short value2) {
            addCriterion("IS_CANCEL between", value1, value2, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsCancelNotBetween(Short value1, Short value2) {
            addCriterion("IS_CANCEL not between", value1, value2, "isCancel");
            return (Criteria) this;
        }

        public Criteria andIsConTktIsNull() {
            addCriterion("IS_CON_TKT is null");
            return (Criteria) this;
        }

        public Criteria andIsConTktIsNotNull() {
            addCriterion("IS_CON_TKT is not null");
            return (Criteria) this;
        }

        public Criteria andIsConTktEqualTo(Short value) {
            addCriterion("IS_CON_TKT =", value, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsConTktNotEqualTo(Short value) {
            addCriterion("IS_CON_TKT <>", value, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsConTktGreaterThan(Short value) {
            addCriterion("IS_CON_TKT >", value, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsConTktGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_CON_TKT >=", value, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsConTktLessThan(Short value) {
            addCriterion("IS_CON_TKT <", value, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsConTktLessThanOrEqualTo(Short value) {
            addCriterion("IS_CON_TKT <=", value, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsConTktIn(List<Short> values) {
            addCriterion("IS_CON_TKT in", values, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsConTktNotIn(List<Short> values) {
            addCriterion("IS_CON_TKT not in", values, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsConTktBetween(Short value1, Short value2) {
            addCriterion("IS_CON_TKT between", value1, value2, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsConTktNotBetween(Short value1, Short value2) {
            addCriterion("IS_CON_TKT not between", value1, value2, "isConTkt");
            return (Criteria) this;
        }

        public Criteria andIsInterIsNull() {
            addCriterion("IS_INTER is null");
            return (Criteria) this;
        }

        public Criteria andIsInterIsNotNull() {
            addCriterion("IS_INTER is not null");
            return (Criteria) this;
        }

        public Criteria andIsInterEqualTo(Short value) {
            addCriterion("IS_INTER =", value, "isInter");
            return (Criteria) this;
        }

        public Criteria andIsInterNotEqualTo(Short value) {
            addCriterion("IS_INTER <>", value, "isInter");
            return (Criteria) this;
        }

        public Criteria andIsInterGreaterThan(Short value) {
            addCriterion("IS_INTER >", value, "isInter");
            return (Criteria) this;
        }

        public Criteria andIsInterGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_INTER >=", value, "isInter");
            return (Criteria) this;
        }

        public Criteria andIsInterLessThan(Short value) {
            addCriterion("IS_INTER <", value, "isInter");
            return (Criteria) this;
        }

        public Criteria andIsInterLessThanOrEqualTo(Short value) {
            addCriterion("IS_INTER <=", value, "isInter");
            return (Criteria) this;
        }

        public Criteria andIsInterIn(List<Short> values) {
            addCriterion("IS_INTER in", values, "isInter");
            return (Criteria) this;
        }

        public Criteria andIsInterNotIn(List<Short> values) {
            addCriterion("IS_INTER not in", values, "isInter");
            return (Criteria) this;
        }

        public Criteria andIsInterBetween(Short value1, Short value2) {
            addCriterion("IS_INTER between", value1, value2, "isInter");
            return (Criteria) this;
        }

        public Criteria andIsInterNotBetween(Short value1, Short value2) {
            addCriterion("IS_INTER not between", value1, value2, "isInter");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoIsNull() {
            addCriterion("FIRST_TKT_NO is null");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoIsNotNull() {
            addCriterion("FIRST_TKT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoEqualTo(String value) {
            addCriterion("FIRST_TKT_NO =", value, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoNotEqualTo(String value) {
            addCriterion("FIRST_TKT_NO <>", value, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoGreaterThan(String value) {
            addCriterion("FIRST_TKT_NO >", value, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoGreaterThanOrEqualTo(String value) {
            addCriterion("FIRST_TKT_NO >=", value, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoLessThan(String value) {
            addCriterion("FIRST_TKT_NO <", value, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoLessThanOrEqualTo(String value) {
            addCriterion("FIRST_TKT_NO <=", value, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoLike(String value) {
            addCriterion("FIRST_TKT_NO like", value, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoNotLike(String value) {
            addCriterion("FIRST_TKT_NO not like", value, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoIn(List<String> values) {
            addCriterion("FIRST_TKT_NO in", values, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoNotIn(List<String> values) {
            addCriterion("FIRST_TKT_NO not in", values, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoBetween(String value1, String value2) {
            addCriterion("FIRST_TKT_NO between", value1, value2, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andFirstTktNoNotBetween(String value1, String value2) {
            addCriterion("FIRST_TKT_NO not between", value1, value2, "firstTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoIsNull() {
            addCriterion("SECOND_TKT_NO is null");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoIsNotNull() {
            addCriterion("SECOND_TKT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoEqualTo(String value) {
            addCriterion("SECOND_TKT_NO =", value, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoNotEqualTo(String value) {
            addCriterion("SECOND_TKT_NO <>", value, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoGreaterThan(String value) {
            addCriterion("SECOND_TKT_NO >", value, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoGreaterThanOrEqualTo(String value) {
            addCriterion("SECOND_TKT_NO >=", value, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoLessThan(String value) {
            addCriterion("SECOND_TKT_NO <", value, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoLessThanOrEqualTo(String value) {
            addCriterion("SECOND_TKT_NO <=", value, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoLike(String value) {
            addCriterion("SECOND_TKT_NO like", value, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoNotLike(String value) {
            addCriterion("SECOND_TKT_NO not like", value, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoIn(List<String> values) {
            addCriterion("SECOND_TKT_NO in", values, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoNotIn(List<String> values) {
            addCriterion("SECOND_TKT_NO not in", values, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoBetween(String value1, String value2) {
            addCriterion("SECOND_TKT_NO between", value1, value2, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andSecondTktNoNotBetween(String value1, String value2) {
            addCriterion("SECOND_TKT_NO not between", value1, value2, "secondTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoIsNull() {
            addCriterion("THIRD_TKT_NO is null");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoIsNotNull() {
            addCriterion("THIRD_TKT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoEqualTo(String value) {
            addCriterion("THIRD_TKT_NO =", value, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoNotEqualTo(String value) {
            addCriterion("THIRD_TKT_NO <>", value, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoGreaterThan(String value) {
            addCriterion("THIRD_TKT_NO >", value, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoGreaterThanOrEqualTo(String value) {
            addCriterion("THIRD_TKT_NO >=", value, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoLessThan(String value) {
            addCriterion("THIRD_TKT_NO <", value, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoLessThanOrEqualTo(String value) {
            addCriterion("THIRD_TKT_NO <=", value, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoLike(String value) {
            addCriterion("THIRD_TKT_NO like", value, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoNotLike(String value) {
            addCriterion("THIRD_TKT_NO not like", value, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoIn(List<String> values) {
            addCriterion("THIRD_TKT_NO in", values, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoNotIn(List<String> values) {
            addCriterion("THIRD_TKT_NO not in", values, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoBetween(String value1, String value2) {
            addCriterion("THIRD_TKT_NO between", value1, value2, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andThirdTktNoNotBetween(String value1, String value2) {
            addCriterion("THIRD_TKT_NO not between", value1, value2, "thirdTktNo");
            return (Criteria) this;
        }

        public Criteria andPaxIdIsNull() {
            addCriterion("PAX_ID is null");
            return (Criteria) this;
        }

        public Criteria andPaxIdIsNotNull() {
            addCriterion("PAX_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPaxIdEqualTo(Long value) {
            addCriterion("PAX_ID =", value, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxIdNotEqualTo(Long value) {
            addCriterion("PAX_ID <>", value, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxIdGreaterThan(Long value) {
            addCriterion("PAX_ID >", value, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PAX_ID >=", value, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxIdLessThan(Long value) {
            addCriterion("PAX_ID <", value, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxIdLessThanOrEqualTo(Long value) {
            addCriterion("PAX_ID <=", value, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxIdIn(List<Long> values) {
            addCriterion("PAX_ID in", values, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxIdNotIn(List<Long> values) {
            addCriterion("PAX_ID not in", values, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxIdBetween(Long value1, Long value2) {
            addCriterion("PAX_ID between", value1, value2, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxIdNotBetween(Long value1, Long value2) {
            addCriterion("PAX_ID not between", value1, value2, "paxId");
            return (Criteria) this;
        }

        public Criteria andPaxNameIsNull() {
            addCriterion("PAX_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPaxNameIsNotNull() {
            addCriterion("PAX_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPaxNameEqualTo(String value) {
            addCriterion("PAX_NAME =", value, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameNotEqualTo(String value) {
            addCriterion("PAX_NAME <>", value, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameGreaterThan(String value) {
            addCriterion("PAX_NAME >", value, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameGreaterThanOrEqualTo(String value) {
            addCriterion("PAX_NAME >=", value, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameLessThan(String value) {
            addCriterion("PAX_NAME <", value, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameLessThanOrEqualTo(String value) {
            addCriterion("PAX_NAME <=", value, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameLike(String value) {
            addCriterion("PAX_NAME like", value, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameNotLike(String value) {
            addCriterion("PAX_NAME not like", value, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameIn(List<String> values) {
            addCriterion("PAX_NAME in", values, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameNotIn(List<String> values) {
            addCriterion("PAX_NAME not in", values, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameBetween(String value1, String value2) {
            addCriterion("PAX_NAME between", value1, value2, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxNameNotBetween(String value1, String value2) {
            addCriterion("PAX_NAME not between", value1, value2, "paxName");
            return (Criteria) this;
        }

        public Criteria andPaxTypeIsNull() {
            addCriterion("PAX_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPaxTypeIsNotNull() {
            addCriterion("PAX_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPaxTypeEqualTo(String value) {
            addCriterion("PAX_TYPE =", value, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeNotEqualTo(String value) {
            addCriterion("PAX_TYPE <>", value, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeGreaterThan(String value) {
            addCriterion("PAX_TYPE >", value, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PAX_TYPE >=", value, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeLessThan(String value) {
            addCriterion("PAX_TYPE <", value, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeLessThanOrEqualTo(String value) {
            addCriterion("PAX_TYPE <=", value, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeLike(String value) {
            addCriterion("PAX_TYPE like", value, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeNotLike(String value) {
            addCriterion("PAX_TYPE not like", value, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeIn(List<String> values) {
            addCriterion("PAX_TYPE in", values, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeNotIn(List<String> values) {
            addCriterion("PAX_TYPE not in", values, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeBetween(String value1, String value2) {
            addCriterion("PAX_TYPE between", value1, value2, "paxType");
            return (Criteria) this;
        }

        public Criteria andPaxTypeNotBetween(String value1, String value2) {
            addCriterion("PAX_TYPE not between", value1, value2, "paxType");
            return (Criteria) this;
        }

        public Criteria andTktAmtIsNull() {
            addCriterion("TKT_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTktAmtIsNotNull() {
            addCriterion("TKT_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTktAmtEqualTo(BigDecimal value) {
            addCriterion("TKT_AMT =", value, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTktAmtNotEqualTo(BigDecimal value) {
            addCriterion("TKT_AMT <>", value, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTktAmtGreaterThan(BigDecimal value) {
            addCriterion("TKT_AMT >", value, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTktAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TKT_AMT >=", value, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTktAmtLessThan(BigDecimal value) {
            addCriterion("TKT_AMT <", value, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTktAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TKT_AMT <=", value, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTktAmtIn(List<BigDecimal> values) {
            addCriterion("TKT_AMT in", values, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTktAmtNotIn(List<BigDecimal> values) {
            addCriterion("TKT_AMT not in", values, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTktAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TKT_AMT between", value1, value2, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTktAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TKT_AMT not between", value1, value2, "tktAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtIsNull() {
            addCriterion("TAX_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTaxAmtIsNotNull() {
            addCriterion("TAX_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTaxAmtEqualTo(BigDecimal value) {
            addCriterion("TAX_AMT =", value, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtNotEqualTo(BigDecimal value) {
            addCriterion("TAX_AMT <>", value, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtGreaterThan(BigDecimal value) {
            addCriterion("TAX_AMT >", value, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TAX_AMT >=", value, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtLessThan(BigDecimal value) {
            addCriterion("TAX_AMT <", value, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TAX_AMT <=", value, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtIn(List<BigDecimal> values) {
            addCriterion("TAX_AMT in", values, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtNotIn(List<BigDecimal> values) {
            addCriterion("TAX_AMT not in", values, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TAX_AMT between", value1, value2, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andTaxAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TAX_AMT not between", value1, value2, "taxAmt");
            return (Criteria) this;
        }

        public Criteria andFpIsNull() {
            addCriterion("FP is null");
            return (Criteria) this;
        }

        public Criteria andFpIsNotNull() {
            addCriterion("FP is not null");
            return (Criteria) this;
        }

        public Criteria andFpEqualTo(String value) {
            addCriterion("FP =", value, "fp");
            return (Criteria) this;
        }

        public Criteria andFpNotEqualTo(String value) {
            addCriterion("FP <>", value, "fp");
            return (Criteria) this;
        }

        public Criteria andFpGreaterThan(String value) {
            addCriterion("FP >", value, "fp");
            return (Criteria) this;
        }

        public Criteria andFpGreaterThanOrEqualTo(String value) {
            addCriterion("FP >=", value, "fp");
            return (Criteria) this;
        }

        public Criteria andFpLessThan(String value) {
            addCriterion("FP <", value, "fp");
            return (Criteria) this;
        }

        public Criteria andFpLessThanOrEqualTo(String value) {
            addCriterion("FP <=", value, "fp");
            return (Criteria) this;
        }

        public Criteria andFpLike(String value) {
            addCriterion("FP like", value, "fp");
            return (Criteria) this;
        }

        public Criteria andFpNotLike(String value) {
            addCriterion("FP not like", value, "fp");
            return (Criteria) this;
        }

        public Criteria andFpIn(List<String> values) {
            addCriterion("FP in", values, "fp");
            return (Criteria) this;
        }

        public Criteria andFpNotIn(List<String> values) {
            addCriterion("FP not in", values, "fp");
            return (Criteria) this;
        }

        public Criteria andFpBetween(String value1, String value2) {
            addCriterion("FP between", value1, value2, "fp");
            return (Criteria) this;
        }

        public Criteria andFpNotBetween(String value1, String value2) {
            addCriterion("FP not between", value1, value2, "fp");
            return (Criteria) this;
        }

        public Criteria andOfficeNoIsNull() {
            addCriterion("OFFICE_NO is null");
            return (Criteria) this;
        }

        public Criteria andOfficeNoIsNotNull() {
            addCriterion("OFFICE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeNoEqualTo(String value) {
            addCriterion("OFFICE_NO =", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotEqualTo(String value) {
            addCriterion("OFFICE_NO <>", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoGreaterThan(String value) {
            addCriterion("OFFICE_NO >", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoGreaterThanOrEqualTo(String value) {
            addCriterion("OFFICE_NO >=", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoLessThan(String value) {
            addCriterion("OFFICE_NO <", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoLessThanOrEqualTo(String value) {
            addCriterion("OFFICE_NO <=", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoLike(String value) {
            addCriterion("OFFICE_NO like", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotLike(String value) {
            addCriterion("OFFICE_NO not like", value, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoIn(List<String> values) {
            addCriterion("OFFICE_NO in", values, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotIn(List<String> values) {
            addCriterion("OFFICE_NO not in", values, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoBetween(String value1, String value2) {
            addCriterion("OFFICE_NO between", value1, value2, "officeNo");
            return (Criteria) this;
        }

        public Criteria andOfficeNoNotBetween(String value1, String value2) {
            addCriterion("OFFICE_NO not between", value1, value2, "officeNo");
            return (Criteria) this;
        }

        public Criteria andIataNoIsNull() {
            addCriterion("IATA_NO is null");
            return (Criteria) this;
        }

        public Criteria andIataNoIsNotNull() {
            addCriterion("IATA_NO is not null");
            return (Criteria) this;
        }

        public Criteria andIataNoEqualTo(String value) {
            addCriterion("IATA_NO =", value, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoNotEqualTo(String value) {
            addCriterion("IATA_NO <>", value, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoGreaterThan(String value) {
            addCriterion("IATA_NO >", value, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoGreaterThanOrEqualTo(String value) {
            addCriterion("IATA_NO >=", value, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoLessThan(String value) {
            addCriterion("IATA_NO <", value, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoLessThanOrEqualTo(String value) {
            addCriterion("IATA_NO <=", value, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoLike(String value) {
            addCriterion("IATA_NO like", value, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoNotLike(String value) {
            addCriterion("IATA_NO not like", value, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoIn(List<String> values) {
            addCriterion("IATA_NO in", values, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoNotIn(List<String> values) {
            addCriterion("IATA_NO not in", values, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoBetween(String value1, String value2) {
            addCriterion("IATA_NO between", value1, value2, "iataNo");
            return (Criteria) this;
        }

        public Criteria andIataNoNotBetween(String value1, String value2) {
            addCriterion("IATA_NO not between", value1, value2, "iataNo");
            return (Criteria) this;
        }

        public Criteria andEtdzDateIsNull() {
            addCriterion("ETDZ_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEtdzDateIsNotNull() {
            addCriterion("ETDZ_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEtdzDateEqualTo(Date value) {
            addCriterionForJDBCDate("ETDZ_DATE =", value, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andEtdzDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ETDZ_DATE <>", value, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andEtdzDateGreaterThan(Date value) {
            addCriterionForJDBCDate("ETDZ_DATE >", value, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andEtdzDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ETDZ_DATE >=", value, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andEtdzDateLessThan(Date value) {
            addCriterionForJDBCDate("ETDZ_DATE <", value, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andEtdzDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ETDZ_DATE <=", value, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andEtdzDateIn(List<Date> values) {
            addCriterionForJDBCDate("ETDZ_DATE in", values, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andEtdzDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ETDZ_DATE not in", values, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andEtdzDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ETDZ_DATE between", value1, value2, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andEtdzDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ETDZ_DATE not between", value1, value2, "etdzDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateIsNull() {
            addCriterion("EXPIR_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExpirDateIsNotNull() {
            addCriterion("EXPIR_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpirDateEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIR_DATE =", value, "expirDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIR_DATE <>", value, "expirDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateGreaterThan(Date value) {
            addCriterionForJDBCDate("EXPIR_DATE >", value, "expirDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIR_DATE >=", value, "expirDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateLessThan(Date value) {
            addCriterionForJDBCDate("EXPIR_DATE <", value, "expirDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIR_DATE <=", value, "expirDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIR_DATE in", values, "expirDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIR_DATE not in", values, "expirDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIR_DATE between", value1, value2, "expirDate");
            return (Criteria) this;
        }

        public Criteria andExpirDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIR_DATE not between", value1, value2, "expirDate");
            return (Criteria) this;
        }

        public Criteria andPnrNoIsNull() {
            addCriterion("PNR_NO is null");
            return (Criteria) this;
        }

        public Criteria andPnrNoIsNotNull() {
            addCriterion("PNR_NO is not null");
            return (Criteria) this;
        }

        public Criteria andPnrNoEqualTo(String value) {
            addCriterion("PNR_NO =", value, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoNotEqualTo(String value) {
            addCriterion("PNR_NO <>", value, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoGreaterThan(String value) {
            addCriterion("PNR_NO >", value, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoGreaterThanOrEqualTo(String value) {
            addCriterion("PNR_NO >=", value, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoLessThan(String value) {
            addCriterion("PNR_NO <", value, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoLessThanOrEqualTo(String value) {
            addCriterion("PNR_NO <=", value, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoLike(String value) {
            addCriterion("PNR_NO like", value, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoNotLike(String value) {
            addCriterion("PNR_NO not like", value, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoIn(List<String> values) {
            addCriterion("PNR_NO in", values, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoNotIn(List<String> values) {
            addCriterion("PNR_NO not in", values, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoBetween(String value1, String value2) {
            addCriterion("PNR_NO between", value1, value2, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andPnrNoNotBetween(String value1, String value2) {
            addCriterion("PNR_NO not between", value1, value2, "pnrNo");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterIsNull() {
            addCriterion("ETDZ_PRINTER is null");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterIsNotNull() {
            addCriterion("ETDZ_PRINTER is not null");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterEqualTo(String value) {
            addCriterion("ETDZ_PRINTER =", value, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterNotEqualTo(String value) {
            addCriterion("ETDZ_PRINTER <>", value, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterGreaterThan(String value) {
            addCriterion("ETDZ_PRINTER >", value, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterGreaterThanOrEqualTo(String value) {
            addCriterion("ETDZ_PRINTER >=", value, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterLessThan(String value) {
            addCriterion("ETDZ_PRINTER <", value, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterLessThanOrEqualTo(String value) {
            addCriterion("ETDZ_PRINTER <=", value, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterLike(String value) {
            addCriterion("ETDZ_PRINTER like", value, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterNotLike(String value) {
            addCriterion("ETDZ_PRINTER not like", value, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterIn(List<String> values) {
            addCriterion("ETDZ_PRINTER in", values, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterNotIn(List<String> values) {
            addCriterion("ETDZ_PRINTER not in", values, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterBetween(String value1, String value2) {
            addCriterion("ETDZ_PRINTER between", value1, value2, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andEtdzPrinterNotBetween(String value1, String value2) {
            addCriterion("ETDZ_PRINTER not between", value1, value2, "etdzPrinter");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIsNull() {
            addCriterion("CURRENCY_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIsNotNull() {
            addCriterion("CURRENCY_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeEqualTo(String value) {
            addCriterion("CURRENCY_TYPE =", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotEqualTo(String value) {
            addCriterion("CURRENCY_TYPE <>", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeGreaterThan(String value) {
            addCriterion("CURRENCY_TYPE >", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCY_TYPE >=", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLessThan(String value) {
            addCriterion("CURRENCY_TYPE <", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLessThanOrEqualTo(String value) {
            addCriterion("CURRENCY_TYPE <=", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLike(String value) {
            addCriterion("CURRENCY_TYPE like", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotLike(String value) {
            addCriterion("CURRENCY_TYPE not like", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIn(List<String> values) {
            addCriterion("CURRENCY_TYPE in", values, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotIn(List<String> values) {
            addCriterion("CURRENCY_TYPE not in", values, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeBetween(String value1, String value2) {
            addCriterion("CURRENCY_TYPE between", value1, value2, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotBetween(String value1, String value2) {
            addCriterion("CURRENCY_TYPE not between", value1, value2, "currencyType");
            return (Criteria) this;
        }

        public Criteria andPnrIdIsNull() {
            addCriterion("PNR_ID is null");
            return (Criteria) this;
        }

        public Criteria andPnrIdIsNotNull() {
            addCriterion("PNR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPnrIdEqualTo(Long value) {
            addCriterion("PNR_ID =", value, "pnrId");
            return (Criteria) this;
        }

        public Criteria andPnrIdNotEqualTo(Long value) {
            addCriterion("PNR_ID <>", value, "pnrId");
            return (Criteria) this;
        }

        public Criteria andPnrIdGreaterThan(Long value) {
            addCriterion("PNR_ID >", value, "pnrId");
            return (Criteria) this;
        }

        public Criteria andPnrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PNR_ID >=", value, "pnrId");
            return (Criteria) this;
        }

        public Criteria andPnrIdLessThan(Long value) {
            addCriterion("PNR_ID <", value, "pnrId");
            return (Criteria) this;
        }

        public Criteria andPnrIdLessThanOrEqualTo(Long value) {
            addCriterion("PNR_ID <=", value, "pnrId");
            return (Criteria) this;
        }

        public Criteria andPnrIdIn(List<Long> values) {
            addCriterion("PNR_ID in", values, "pnrId");
            return (Criteria) this;
        }

        public Criteria andPnrIdNotIn(List<Long> values) {
            addCriterion("PNR_ID not in", values, "pnrId");
            return (Criteria) this;
        }

        public Criteria andPnrIdBetween(Long value1, Long value2) {
            addCriterion("PNR_ID between", value1, value2, "pnrId");
            return (Criteria) this;
        }

        public Criteria andPnrIdNotBetween(Long value1, Long value2) {
            addCriterion("PNR_ID not between", value1, value2, "pnrId");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoIsNull() {
            addCriterion("AIR_ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoIsNotNull() {
            addCriterion("AIR_ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoEqualTo(Long value) {
            addCriterion("AIR_ORDER_NO =", value, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoNotEqualTo(Long value) {
            addCriterion("AIR_ORDER_NO <>", value, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoGreaterThan(Long value) {
            addCriterion("AIR_ORDER_NO >", value, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("AIR_ORDER_NO >=", value, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoLessThan(Long value) {
            addCriterion("AIR_ORDER_NO <", value, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("AIR_ORDER_NO <=", value, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoIn(List<Long> values) {
            addCriterion("AIR_ORDER_NO in", values, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoNotIn(List<Long> values) {
            addCriterion("AIR_ORDER_NO not in", values, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoBetween(Long value1, Long value2) {
            addCriterion("AIR_ORDER_NO between", value1, value2, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andAirOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("AIR_ORDER_NO not between", value1, value2, "airOrderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(Long value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(Long value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(Long value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(Long value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<Long> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<Long> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(Long value1, Long value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoIsNull() {
            addCriterion("CHANNEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andChannelNoIsNotNull() {
            addCriterion("CHANNEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNoEqualTo(Short value) {
            addCriterion("CHANNEL_NO =", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoNotEqualTo(Short value) {
            addCriterion("CHANNEL_NO <>", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoGreaterThan(Short value) {
            addCriterion("CHANNEL_NO >", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoGreaterThanOrEqualTo(Short value) {
            addCriterion("CHANNEL_NO >=", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoLessThan(Short value) {
            addCriterion("CHANNEL_NO <", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoLessThanOrEqualTo(Short value) {
            addCriterion("CHANNEL_NO <=", value, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoIn(List<Short> values) {
            addCriterion("CHANNEL_NO in", values, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoNotIn(List<Short> values) {
            addCriterion("CHANNEL_NO not in", values, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoBetween(Short value1, Short value2) {
            addCriterion("CHANNEL_NO between", value1, value2, "channelNo");
            return (Criteria) this;
        }

        public Criteria andChannelNoNotBetween(Short value1, Short value2) {
            addCriterion("CHANNEL_NO not between", value1, value2, "channelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoIsNull() {
            addCriterion("SECOND_CHANNEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoIsNotNull() {
            addCriterion("SECOND_CHANNEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoEqualTo(String value) {
            addCriterion("SECOND_CHANNEL_NO =", value, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoNotEqualTo(String value) {
            addCriterion("SECOND_CHANNEL_NO <>", value, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoGreaterThan(String value) {
            addCriterion("SECOND_CHANNEL_NO >", value, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoGreaterThanOrEqualTo(String value) {
            addCriterion("SECOND_CHANNEL_NO >=", value, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoLessThan(String value) {
            addCriterion("SECOND_CHANNEL_NO <", value, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoLessThanOrEqualTo(String value) {
            addCriterion("SECOND_CHANNEL_NO <=", value, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoLike(String value) {
            addCriterion("SECOND_CHANNEL_NO like", value, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoNotLike(String value) {
            addCriterion("SECOND_CHANNEL_NO not like", value, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoIn(List<String> values) {
            addCriterion("SECOND_CHANNEL_NO in", values, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoNotIn(List<String> values) {
            addCriterion("SECOND_CHANNEL_NO not in", values, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoBetween(String value1, String value2) {
            addCriterion("SECOND_CHANNEL_NO between", value1, value2, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andSecondChannelNoNotBetween(String value1, String value2) {
            addCriterion("SECOND_CHANNEL_NO not between", value1, value2, "secondChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoIsNull() {
            addCriterion("THIRD_CHANNEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoIsNotNull() {
            addCriterion("THIRD_CHANNEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoEqualTo(String value) {
            addCriterion("THIRD_CHANNEL_NO =", value, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoNotEqualTo(String value) {
            addCriterion("THIRD_CHANNEL_NO <>", value, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoGreaterThan(String value) {
            addCriterion("THIRD_CHANNEL_NO >", value, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoGreaterThanOrEqualTo(String value) {
            addCriterion("THIRD_CHANNEL_NO >=", value, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoLessThan(String value) {
            addCriterion("THIRD_CHANNEL_NO <", value, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoLessThanOrEqualTo(String value) {
            addCriterion("THIRD_CHANNEL_NO <=", value, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoLike(String value) {
            addCriterion("THIRD_CHANNEL_NO like", value, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoNotLike(String value) {
            addCriterion("THIRD_CHANNEL_NO not like", value, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoIn(List<String> values) {
            addCriterion("THIRD_CHANNEL_NO in", values, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoNotIn(List<String> values) {
            addCriterion("THIRD_CHANNEL_NO not in", values, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoBetween(String value1, String value2) {
            addCriterion("THIRD_CHANNEL_NO between", value1, value2, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andThirdChannelNoNotBetween(String value1, String value2) {
            addCriterion("THIRD_CHANNEL_NO not between", value1, value2, "thirdChannelNo");
            return (Criteria) this;
        }

        public Criteria andSiteCodeIsNull() {
            addCriterion("SITE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSiteCodeIsNotNull() {
            addCriterion("SITE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSiteCodeEqualTo(String value) {
            addCriterion("SITE_CODE =", value, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeNotEqualTo(String value) {
            addCriterion("SITE_CODE <>", value, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeGreaterThan(String value) {
            addCriterion("SITE_CODE >", value, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SITE_CODE >=", value, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeLessThan(String value) {
            addCriterion("SITE_CODE <", value, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeLessThanOrEqualTo(String value) {
            addCriterion("SITE_CODE <=", value, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeLike(String value) {
            addCriterion("SITE_CODE like", value, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeNotLike(String value) {
            addCriterion("SITE_CODE not like", value, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeIn(List<String> values) {
            addCriterion("SITE_CODE in", values, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeNotIn(List<String> values) {
            addCriterion("SITE_CODE not in", values, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeBetween(String value1, String value2) {
            addCriterion("SITE_CODE between", value1, value2, "siteCode");
            return (Criteria) this;
        }

        public Criteria andSiteCodeNotBetween(String value1, String value2) {
            addCriterion("SITE_CODE not between", value1, value2, "siteCode");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("IS_VALID is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("IS_VALID is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Short value) {
            addCriterion("IS_VALID =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Short value) {
            addCriterion("IS_VALID <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Short value) {
            addCriterion("IS_VALID >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_VALID >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Short value) {
            addCriterion("IS_VALID <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Short value) {
            addCriterion("IS_VALID <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Short> values) {
            addCriterion("IS_VALID in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Short> values) {
            addCriterion("IS_VALID not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Short value1, Short value2) {
            addCriterion("IS_VALID between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Short value1, Short value2) {
            addCriterion("IS_VALID not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andCrtIdIsNull() {
            addCriterion("CRT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrtIdIsNotNull() {
            addCriterion("CRT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrtIdEqualTo(String value) {
            addCriterion("CRT_ID =", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotEqualTo(String value) {
            addCriterion("CRT_ID <>", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdGreaterThan(String value) {
            addCriterion("CRT_ID >", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdGreaterThanOrEqualTo(String value) {
            addCriterion("CRT_ID >=", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdLessThan(String value) {
            addCriterion("CRT_ID <", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdLessThanOrEqualTo(String value) {
            addCriterion("CRT_ID <=", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdLike(String value) {
            addCriterion("CRT_ID like", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotLike(String value) {
            addCriterion("CRT_ID not like", value, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdIn(List<String> values) {
            addCriterion("CRT_ID in", values, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotIn(List<String> values) {
            addCriterion("CRT_ID not in", values, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdBetween(String value1, String value2) {
            addCriterion("CRT_ID between", value1, value2, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtIdNotBetween(String value1, String value2) {
            addCriterion("CRT_ID not between", value1, value2, "crtId");
            return (Criteria) this;
        }

        public Criteria andCrtDtIsNull() {
            addCriterion("CRT_DT is null");
            return (Criteria) this;
        }

        public Criteria andCrtDtIsNotNull() {
            addCriterion("CRT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCrtDtEqualTo(Date value) {
            addCriterionForJDBCDate("CRT_DT =", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("CRT_DT <>", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtGreaterThan(Date value) {
            addCriterionForJDBCDate("CRT_DT >", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CRT_DT >=", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtLessThan(Date value) {
            addCriterionForJDBCDate("CRT_DT <", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CRT_DT <=", value, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtIn(List<Date> values) {
            addCriterionForJDBCDate("CRT_DT in", values, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("CRT_DT not in", values, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CRT_DT between", value1, value2, "crtDt");
            return (Criteria) this;
        }

        public Criteria andCrtDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CRT_DT not between", value1, value2, "crtDt");
            return (Criteria) this;
        }

        public Criteria andOptIdIsNull() {
            addCriterion("OPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andOptIdIsNotNull() {
            addCriterion("OPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOptIdEqualTo(String value) {
            addCriterion("OPT_ID =", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotEqualTo(String value) {
            addCriterion("OPT_ID <>", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdGreaterThan(String value) {
            addCriterion("OPT_ID >", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPT_ID >=", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdLessThan(String value) {
            addCriterion("OPT_ID <", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdLessThanOrEqualTo(String value) {
            addCriterion("OPT_ID <=", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdLike(String value) {
            addCriterion("OPT_ID like", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotLike(String value) {
            addCriterion("OPT_ID not like", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdIn(List<String> values) {
            addCriterion("OPT_ID in", values, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotIn(List<String> values) {
            addCriterion("OPT_ID not in", values, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdBetween(String value1, String value2) {
            addCriterion("OPT_ID between", value1, value2, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotBetween(String value1, String value2) {
            addCriterion("OPT_ID not between", value1, value2, "optId");
            return (Criteria) this;
        }

        public Criteria andOptDtIsNull() {
            addCriterion("OPT_DT is null");
            return (Criteria) this;
        }

        public Criteria andOptDtIsNotNull() {
            addCriterion("OPT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andOptDtEqualTo(Date value) {
            addCriterionForJDBCDate("OPT_DT =", value, "optDt");
            return (Criteria) this;
        }

        public Criteria andOptDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("OPT_DT <>", value, "optDt");
            return (Criteria) this;
        }

        public Criteria andOptDtGreaterThan(Date value) {
            addCriterionForJDBCDate("OPT_DT >", value, "optDt");
            return (Criteria) this;
        }

        public Criteria andOptDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OPT_DT >=", value, "optDt");
            return (Criteria) this;
        }

        public Criteria andOptDtLessThan(Date value) {
            addCriterionForJDBCDate("OPT_DT <", value, "optDt");
            return (Criteria) this;
        }

        public Criteria andOptDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OPT_DT <=", value, "optDt");
            return (Criteria) this;
        }

        public Criteria andOptDtIn(List<Date> values) {
            addCriterionForJDBCDate("OPT_DT in", values, "optDt");
            return (Criteria) this;
        }

        public Criteria andOptDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("OPT_DT not in", values, "optDt");
            return (Criteria) this;
        }

        public Criteria andOptDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OPT_DT between", value1, value2, "optDt");
            return (Criteria) this;
        }

        public Criteria andOptDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OPT_DT not between", value1, value2, "optDt");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andIsPrintIsNull() {
            addCriterion("IS_PRINT is null");
            return (Criteria) this;
        }

        public Criteria andIsPrintIsNotNull() {
            addCriterion("IS_PRINT is not null");
            return (Criteria) this;
        }

        public Criteria andIsPrintEqualTo(Short value) {
            addCriterion("IS_PRINT =", value, "isPrint");
            return (Criteria) this;
        }

        public Criteria andIsPrintNotEqualTo(Short value) {
            addCriterion("IS_PRINT <>", value, "isPrint");
            return (Criteria) this;
        }

        public Criteria andIsPrintGreaterThan(Short value) {
            addCriterion("IS_PRINT >", value, "isPrint");
            return (Criteria) this;
        }

        public Criteria andIsPrintGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_PRINT >=", value, "isPrint");
            return (Criteria) this;
        }

        public Criteria andIsPrintLessThan(Short value) {
            addCriterion("IS_PRINT <", value, "isPrint");
            return (Criteria) this;
        }

        public Criteria andIsPrintLessThanOrEqualTo(Short value) {
            addCriterion("IS_PRINT <=", value, "isPrint");
            return (Criteria) this;
        }

        public Criteria andIsPrintIn(List<Short> values) {
            addCriterion("IS_PRINT in", values, "isPrint");
            return (Criteria) this;
        }

        public Criteria andIsPrintNotIn(List<Short> values) {
            addCriterion("IS_PRINT not in", values, "isPrint");
            return (Criteria) this;
        }

        public Criteria andIsPrintBetween(Short value1, Short value2) {
            addCriterion("IS_PRINT between", value1, value2, "isPrint");
            return (Criteria) this;
        }

        public Criteria andIsPrintNotBetween(Short value1, Short value2) {
            addCriterion("IS_PRINT not between", value1, value2, "isPrint");
            return (Criteria) this;
        }

        public Criteria andTransFlagIsNull() {
            addCriterion("TRANS_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andTransFlagIsNotNull() {
            addCriterion("TRANS_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andTransFlagEqualTo(Short value) {
            addCriterion("TRANS_FLAG =", value, "transFlag");
            return (Criteria) this;
        }

        public Criteria andTransFlagNotEqualTo(Short value) {
            addCriterion("TRANS_FLAG <>", value, "transFlag");
            return (Criteria) this;
        }

        public Criteria andTransFlagGreaterThan(Short value) {
            addCriterion("TRANS_FLAG >", value, "transFlag");
            return (Criteria) this;
        }

        public Criteria andTransFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("TRANS_FLAG >=", value, "transFlag");
            return (Criteria) this;
        }

        public Criteria andTransFlagLessThan(Short value) {
            addCriterion("TRANS_FLAG <", value, "transFlag");
            return (Criteria) this;
        }

        public Criteria andTransFlagLessThanOrEqualTo(Short value) {
            addCriterion("TRANS_FLAG <=", value, "transFlag");
            return (Criteria) this;
        }

        public Criteria andTransFlagIn(List<Short> values) {
            addCriterion("TRANS_FLAG in", values, "transFlag");
            return (Criteria) this;
        }

        public Criteria andTransFlagNotIn(List<Short> values) {
            addCriterion("TRANS_FLAG not in", values, "transFlag");
            return (Criteria) this;
        }

        public Criteria andTransFlagBetween(Short value1, Short value2) {
            addCriterion("TRANS_FLAG between", value1, value2, "transFlag");
            return (Criteria) this;
        }

        public Criteria andTransFlagNotBetween(Short value1, Short value2) {
            addCriterion("TRANS_FLAG not between", value1, value2, "transFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 22 16:11:20 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UNIORDER.AIR_TKT_INFO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}