package com.wxfeng.mybatis.uniorder;

import java.math.BigDecimal;
import java.util.Date;

public class AirTktInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String tktNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.TRIP_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String tripType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.IS_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.IS_EXCHANGE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isExchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.IS_CANCEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isCancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.IS_CON_TKT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isConTkt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.IS_INTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isInter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.FIRST_TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String firstTktNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.SECOND_TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String secondTktNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.THIRD_TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String thirdTktNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.PAX_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long paxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.PAX_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String paxName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.PAX_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String paxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.TKT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal tktAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal taxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.FP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String fp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.OFFICE_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String officeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.IATA_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String iataNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.ETDZ_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date etdzDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.EXPIR_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date expirDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String pnrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.ETDZ_PRINTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String etdzPrinter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.CURRENCY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String currencyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.PNR_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long pnrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long airOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short channelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.SECOND_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String secondChannelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.THIRD_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String thirdChannelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.SITE_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String siteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String crtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String optId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date optDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.IS_PRINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isPrint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.AIR_TKT_INFO.TRANS_FLAG
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short transFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.ID
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.ID
     *
     * @param id the value for UNIORDER.AIR_TKT_INFO.ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.TKT_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getTktNo() {
        return tktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.TKT_NO
     *
     * @param tktNo the value for UNIORDER.AIR_TKT_INFO.TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTktNo(String tktNo) {
        this.tktNo = tktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.TRIP_TYPE
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.TRIP_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getTripType() {
        return tripType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.TRIP_TYPE
     *
     * @param tripType the value for UNIORDER.AIR_TKT_INFO.TRIP_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTripType(String tripType) {
        this.tripType = tripType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.IS_POINT
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.IS_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsPoint() {
        return isPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.IS_POINT
     *
     * @param isPoint the value for UNIORDER.AIR_TKT_INFO.IS_POINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsPoint(Short isPoint) {
        this.isPoint = isPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.IS_EXCHANGE
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.IS_EXCHANGE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsExchange() {
        return isExchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.IS_EXCHANGE
     *
     * @param isExchange the value for UNIORDER.AIR_TKT_INFO.IS_EXCHANGE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsExchange(Short isExchange) {
        this.isExchange = isExchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.IS_CANCEL
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.IS_CANCEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsCancel() {
        return isCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.IS_CANCEL
     *
     * @param isCancel the value for UNIORDER.AIR_TKT_INFO.IS_CANCEL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsCancel(Short isCancel) {
        this.isCancel = isCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.IS_CON_TKT
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.IS_CON_TKT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsConTkt() {
        return isConTkt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.IS_CON_TKT
     *
     * @param isConTkt the value for UNIORDER.AIR_TKT_INFO.IS_CON_TKT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsConTkt(Short isConTkt) {
        this.isConTkt = isConTkt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.IS_INTER
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.IS_INTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsInter() {
        return isInter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.IS_INTER
     *
     * @param isInter the value for UNIORDER.AIR_TKT_INFO.IS_INTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsInter(Short isInter) {
        this.isInter = isInter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.FIRST_TKT_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.FIRST_TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFirstTktNo() {
        return firstTktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.FIRST_TKT_NO
     *
     * @param firstTktNo the value for UNIORDER.AIR_TKT_INFO.FIRST_TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFirstTktNo(String firstTktNo) {
        this.firstTktNo = firstTktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.SECOND_TKT_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.SECOND_TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSecondTktNo() {
        return secondTktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.SECOND_TKT_NO
     *
     * @param secondTktNo the value for UNIORDER.AIR_TKT_INFO.SECOND_TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSecondTktNo(String secondTktNo) {
        this.secondTktNo = secondTktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.THIRD_TKT_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.THIRD_TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getThirdTktNo() {
        return thirdTktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.THIRD_TKT_NO
     *
     * @param thirdTktNo the value for UNIORDER.AIR_TKT_INFO.THIRD_TKT_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setThirdTktNo(String thirdTktNo) {
        this.thirdTktNo = thirdTktNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.PAX_ID
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.PAX_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getPaxId() {
        return paxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.PAX_ID
     *
     * @param paxId the value for UNIORDER.AIR_TKT_INFO.PAX_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxId(Long paxId) {
        this.paxId = paxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.PAX_NAME
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.PAX_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPaxName() {
        return paxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.PAX_NAME
     *
     * @param paxName the value for UNIORDER.AIR_TKT_INFO.PAX_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxName(String paxName) {
        this.paxName = paxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.PAX_TYPE
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.PAX_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPaxType() {
        return paxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.PAX_TYPE
     *
     * @param paxType the value for UNIORDER.AIR_TKT_INFO.PAX_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPaxType(String paxType) {
        this.paxType = paxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.TKT_AMT
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.TKT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getTktAmt() {
        return tktAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.TKT_AMT
     *
     * @param tktAmt the value for UNIORDER.AIR_TKT_INFO.TKT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTktAmt(BigDecimal tktAmt) {
        this.tktAmt = tktAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.TAX_AMT
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getTaxAmt() {
        return taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.TAX_AMT
     *
     * @param taxAmt the value for UNIORDER.AIR_TKT_INFO.TAX_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTaxAmt(BigDecimal taxAmt) {
        this.taxAmt = taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.FP
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.FP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getFp() {
        return fp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.FP
     *
     * @param fp the value for UNIORDER.AIR_TKT_INFO.FP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setFp(String fp) {
        this.fp = fp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.OFFICE_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.OFFICE_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOfficeNo() {
        return officeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.OFFICE_NO
     *
     * @param officeNo the value for UNIORDER.AIR_TKT_INFO.OFFICE_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOfficeNo(String officeNo) {
        this.officeNo = officeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.IATA_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.IATA_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getIataNo() {
        return iataNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.IATA_NO
     *
     * @param iataNo the value for UNIORDER.AIR_TKT_INFO.IATA_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIataNo(String iataNo) {
        this.iataNo = iataNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.ETDZ_DATE
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.ETDZ_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getEtdzDate() {
        return etdzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.ETDZ_DATE
     *
     * @param etdzDate the value for UNIORDER.AIR_TKT_INFO.ETDZ_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setEtdzDate(Date etdzDate) {
        this.etdzDate = etdzDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.EXPIR_DATE
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.EXPIR_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getExpirDate() {
        return expirDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.EXPIR_DATE
     *
     * @param expirDate the value for UNIORDER.AIR_TKT_INFO.EXPIR_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setExpirDate(Date expirDate) {
        this.expirDate = expirDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.PNR_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPnrNo() {
        return pnrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.PNR_NO
     *
     * @param pnrNo the value for UNIORDER.AIR_TKT_INFO.PNR_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPnrNo(String pnrNo) {
        this.pnrNo = pnrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.ETDZ_PRINTER
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.ETDZ_PRINTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getEtdzPrinter() {
        return etdzPrinter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.ETDZ_PRINTER
     *
     * @param etdzPrinter the value for UNIORDER.AIR_TKT_INFO.ETDZ_PRINTER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setEtdzPrinter(String etdzPrinter) {
        this.etdzPrinter = etdzPrinter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.CURRENCY_TYPE
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.CURRENCY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.CURRENCY_TYPE
     *
     * @param currencyType the value for UNIORDER.AIR_TKT_INFO.CURRENCY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.PNR_ID
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.PNR_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getPnrId() {
        return pnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.PNR_ID
     *
     * @param pnrId the value for UNIORDER.AIR_TKT_INFO.PNR_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPnrId(Long pnrId) {
        this.pnrId = pnrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.AIR_ORDER_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getAirOrderNo() {
        return airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.AIR_ORDER_NO
     *
     * @param airOrderNo the value for UNIORDER.AIR_TKT_INFO.AIR_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setAirOrderNo(Long airOrderNo) {
        this.airOrderNo = airOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.ORDER_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.ORDER_NO
     *
     * @param orderNo the value for UNIORDER.AIR_TKT_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.CHANNEL_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.CHANNEL_NO
     *
     * @param channelNo the value for UNIORDER.AIR_TKT_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChannelNo(Short channelNo) {
        this.channelNo = channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.SECOND_CHANNEL_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.SECOND_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSecondChannelNo() {
        return secondChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.SECOND_CHANNEL_NO
     *
     * @param secondChannelNo the value for UNIORDER.AIR_TKT_INFO.SECOND_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSecondChannelNo(String secondChannelNo) {
        this.secondChannelNo = secondChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.THIRD_CHANNEL_NO
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.THIRD_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getThirdChannelNo() {
        return thirdChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.THIRD_CHANNEL_NO
     *
     * @param thirdChannelNo the value for UNIORDER.AIR_TKT_INFO.THIRD_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setThirdChannelNo(String thirdChannelNo) {
        this.thirdChannelNo = thirdChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.SITE_CODE
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.SITE_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSiteCode() {
        return siteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.SITE_CODE
     *
     * @param siteCode the value for UNIORDER.AIR_TKT_INFO.SITE_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.REMARK
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.REMARK
     *
     * @param remark the value for UNIORDER.AIR_TKT_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.IS_VALID
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.IS_VALID
     *
     * @param isValid the value for UNIORDER.AIR_TKT_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsValid(Short isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.CRT_ID
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCrtId() {
        return crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.CRT_ID
     *
     * @param crtId the value for UNIORDER.AIR_TKT_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.CRT_DT
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.CRT_DT
     *
     * @param crtDt the value for UNIORDER.AIR_TKT_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtDt(Date crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.OPT_ID
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.OPT_ID
     *
     * @param optId the value for UNIORDER.AIR_TKT_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptId(String optId) {
        this.optId = optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.OPT_DT
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getOptDt() {
        return optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.OPT_DT
     *
     * @param optDt the value for UNIORDER.AIR_TKT_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptDt(Date optDt) {
        this.optDt = optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.VERSION
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.VERSION
     *
     * @param version the value for UNIORDER.AIR_TKT_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.IS_PRINT
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.IS_PRINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsPrint() {
        return isPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.IS_PRINT
     *
     * @param isPrint the value for UNIORDER.AIR_TKT_INFO.IS_PRINT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsPrint(Short isPrint) {
        this.isPrint = isPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.AIR_TKT_INFO.TRANS_FLAG
     *
     * @return the value of UNIORDER.AIR_TKT_INFO.TRANS_FLAG
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getTransFlag() {
        return transFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.AIR_TKT_INFO.TRANS_FLAG
     *
     * @param transFlag the value for UNIORDER.AIR_TKT_INFO.TRANS_FLAG
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTransFlag(Short transFlag) {
        this.transFlag = transFlag;
    }
}