package com.wxfeng.mybatis.uniorder;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.ORDER_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short channelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String secondChannelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String thirdChannelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.SITE_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String siteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.SHOPPING_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String shoppingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.TIME_STAMP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long timeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal payAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String payCurreny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.EXCHANGE_RMB
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal exchangeRmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.POINT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long pointAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CASH_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal cashAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CASH_PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String cashPayCurreny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CASH_EXCHANGE_RMB
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal cashExchangeRmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.COUPON_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal couponAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.COUPON_PAY_UNIT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String couponPayUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.RATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String promoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.PROMO_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String promoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CONTACT_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CONTACT_MOBILE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String contactMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.USER_FFP_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String userFfpNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CONTACT_EMAIL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String contactEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.REQUEST_IP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String requestIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Short isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String crtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date crtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String optId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date optDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.SUB_PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String subPromoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CANCEL_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Date cancelDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.VIP_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String vipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.CALL_CONFIRM_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String callConfirmStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.TRAVEL_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private Long travelOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.ORDER_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.COMPANY_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.RELATED_ORDER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal relatedOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNIORDER.ORDER_INFO.ORI_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    private BigDecimal oriOrderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.ORDER_NO
     *
     * @return the value of UNIORDER.ORDER_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.ORDER_NO
     *
     * @param orderNo the value for UNIORDER.ORDER_INFO.ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.ORDER_STATUS
     *
     * @return the value of UNIORDER.ORDER_INFO.ORDER_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.ORDER_STATUS
     *
     * @param orderStatus the value for UNIORDER.ORDER_INFO.ORDER_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CHANNEL_NO
     *
     * @return the value of UNIORDER.ORDER_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CHANNEL_NO
     *
     * @param channelNo the value for UNIORDER.ORDER_INFO.CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setChannelNo(Short channelNo) {
        this.channelNo = channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @return the value of UNIORDER.ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSecondChannelNo() {
        return secondChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @param secondChannelNo the value for UNIORDER.ORDER_INFO.SECOND_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSecondChannelNo(String secondChannelNo) {
        this.secondChannelNo = secondChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @return the value of UNIORDER.ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getThirdChannelNo() {
        return thirdChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @param thirdChannelNo the value for UNIORDER.ORDER_INFO.THIRD_CHANNEL_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setThirdChannelNo(String thirdChannelNo) {
        this.thirdChannelNo = thirdChannelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.SITE_CODE
     *
     * @return the value of UNIORDER.ORDER_INFO.SITE_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSiteCode() {
        return siteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.SITE_CODE
     *
     * @param siteCode the value for UNIORDER.ORDER_INFO.SITE_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.SHOPPING_TYPE
     *
     * @return the value of UNIORDER.ORDER_INFO.SHOPPING_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getShoppingType() {
        return shoppingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.SHOPPING_TYPE
     *
     * @param shoppingType the value for UNIORDER.ORDER_INFO.SHOPPING_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setShoppingType(String shoppingType) {
        this.shoppingType = shoppingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.PAY_TYPE
     *
     * @return the value of UNIORDER.ORDER_INFO.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.PAY_TYPE
     *
     * @param payType the value for UNIORDER.ORDER_INFO.PAY_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.TIME_STAMP
     *
     * @return the value of UNIORDER.ORDER_INFO.TIME_STAMP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.TIME_STAMP
     *
     * @param timeStamp the value for UNIORDER.ORDER_INFO.TIME_STAMP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.PAY_AMT
     *
     * @return the value of UNIORDER.ORDER_INFO.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getPayAmt() {
        return payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.PAY_AMT
     *
     * @param payAmt the value for UNIORDER.ORDER_INFO.PAY_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayAmt(BigDecimal payAmt) {
        this.payAmt = payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.PAY_CURRENY
     *
     * @return the value of UNIORDER.ORDER_INFO.PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPayCurreny() {
        return payCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.PAY_CURRENY
     *
     * @param payCurreny the value for UNIORDER.ORDER_INFO.PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPayCurreny(String payCurreny) {
        this.payCurreny = payCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.EXCHANGE_RMB
     *
     * @return the value of UNIORDER.ORDER_INFO.EXCHANGE_RMB
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getExchangeRmb() {
        return exchangeRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.EXCHANGE_RMB
     *
     * @param exchangeRmb the value for UNIORDER.ORDER_INFO.EXCHANGE_RMB
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setExchangeRmb(BigDecimal exchangeRmb) {
        this.exchangeRmb = exchangeRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.POINT_AMT
     *
     * @return the value of UNIORDER.ORDER_INFO.POINT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getPointAmt() {
        return pointAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.POINT_AMT
     *
     * @param pointAmt the value for UNIORDER.ORDER_INFO.POINT_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPointAmt(Long pointAmt) {
        this.pointAmt = pointAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CASH_AMT
     *
     * @return the value of UNIORDER.ORDER_INFO.CASH_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getCashAmt() {
        return cashAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CASH_AMT
     *
     * @param cashAmt the value for UNIORDER.ORDER_INFO.CASH_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCashAmt(BigDecimal cashAmt) {
        this.cashAmt = cashAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CASH_PAY_CURRENY
     *
     * @return the value of UNIORDER.ORDER_INFO.CASH_PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCashPayCurreny() {
        return cashPayCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CASH_PAY_CURRENY
     *
     * @param cashPayCurreny the value for UNIORDER.ORDER_INFO.CASH_PAY_CURRENY
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCashPayCurreny(String cashPayCurreny) {
        this.cashPayCurreny = cashPayCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CASH_EXCHANGE_RMB
     *
     * @return the value of UNIORDER.ORDER_INFO.CASH_EXCHANGE_RMB
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getCashExchangeRmb() {
        return cashExchangeRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CASH_EXCHANGE_RMB
     *
     * @param cashExchangeRmb the value for UNIORDER.ORDER_INFO.CASH_EXCHANGE_RMB
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCashExchangeRmb(BigDecimal cashExchangeRmb) {
        this.cashExchangeRmb = cashExchangeRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.COUPON_AMT
     *
     * @return the value of UNIORDER.ORDER_INFO.COUPON_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getCouponAmt() {
        return couponAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.COUPON_AMT
     *
     * @param couponAmt the value for UNIORDER.ORDER_INFO.COUPON_AMT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCouponAmt(BigDecimal couponAmt) {
        this.couponAmt = couponAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.COUPON_PAY_UNIT
     *
     * @return the value of UNIORDER.ORDER_INFO.COUPON_PAY_UNIT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCouponPayUnit() {
        return couponPayUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.COUPON_PAY_UNIT
     *
     * @param couponPayUnit the value for UNIORDER.ORDER_INFO.COUPON_PAY_UNIT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCouponPayUnit(String couponPayUnit) {
        this.couponPayUnit = couponPayUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.RATE
     *
     * @return the value of UNIORDER.ORDER_INFO.RATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.RATE
     *
     * @param rate the value for UNIORDER.ORDER_INFO.RATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.PROMO_TYPE
     *
     * @return the value of UNIORDER.ORDER_INFO.PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPromoType() {
        return promoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.PROMO_TYPE
     *
     * @param promoType the value for UNIORDER.ORDER_INFO.PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPromoType(String promoType) {
        this.promoType = promoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.PROMO_ID
     *
     * @return the value of UNIORDER.ORDER_INFO.PROMO_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getPromoId() {
        return promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.PROMO_ID
     *
     * @param promoId the value for UNIORDER.ORDER_INFO.PROMO_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setPromoId(String promoId) {
        this.promoId = promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CONTACT_NAME
     *
     * @return the value of UNIORDER.ORDER_INFO.CONTACT_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CONTACT_NAME
     *
     * @param contactName the value for UNIORDER.ORDER_INFO.CONTACT_NAME
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CONTACT_MOBILE
     *
     * @return the value of UNIORDER.ORDER_INFO.CONTACT_MOBILE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CONTACT_MOBILE
     *
     * @param contactMobile the value for UNIORDER.ORDER_INFO.CONTACT_MOBILE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.USER_FFP_NO
     *
     * @return the value of UNIORDER.ORDER_INFO.USER_FFP_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getUserFfpNo() {
        return userFfpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.USER_FFP_NO
     *
     * @param userFfpNo the value for UNIORDER.ORDER_INFO.USER_FFP_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setUserFfpNo(String userFfpNo) {
        this.userFfpNo = userFfpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CONTACT_EMAIL
     *
     * @return the value of UNIORDER.ORDER_INFO.CONTACT_EMAIL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CONTACT_EMAIL
     *
     * @param contactEmail the value for UNIORDER.ORDER_INFO.CONTACT_EMAIL
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.REQUEST_IP
     *
     * @return the value of UNIORDER.ORDER_INFO.REQUEST_IP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRequestIp() {
        return requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.REQUEST_IP
     *
     * @param requestIp the value for UNIORDER.ORDER_INFO.REQUEST_IP
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.REMARK
     *
     * @return the value of UNIORDER.ORDER_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.REMARK
     *
     * @param remark the value for UNIORDER.ORDER_INFO.REMARK
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.IS_VALID
     *
     * @return the value of UNIORDER.ORDER_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Short getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.IS_VALID
     *
     * @param isValid the value for UNIORDER.ORDER_INFO.IS_VALID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setIsValid(Short isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CRT_ID
     *
     * @return the value of UNIORDER.ORDER_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCrtId() {
        return crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CRT_ID
     *
     * @param crtId the value for UNIORDER.ORDER_INFO.CRT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtId(String crtId) {
        this.crtId = crtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CRT_DT
     *
     * @return the value of UNIORDER.ORDER_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CRT_DT
     *
     * @param crtDt the value for UNIORDER.ORDER_INFO.CRT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCrtDt(Date crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.OPT_ID
     *
     * @return the value of UNIORDER.ORDER_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.OPT_ID
     *
     * @param optId the value for UNIORDER.ORDER_INFO.OPT_ID
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptId(String optId) {
        this.optId = optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.OPT_DT
     *
     * @return the value of UNIORDER.ORDER_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getOptDt() {
        return optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.OPT_DT
     *
     * @param optDt the value for UNIORDER.ORDER_INFO.OPT_DT
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOptDt(Date optDt) {
        this.optDt = optDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.VERSION
     *
     * @return the value of UNIORDER.ORDER_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.VERSION
     *
     * @param version the value for UNIORDER.ORDER_INFO.VERSION
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.SUB_PROMO_TYPE
     *
     * @return the value of UNIORDER.ORDER_INFO.SUB_PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getSubPromoType() {
        return subPromoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.SUB_PROMO_TYPE
     *
     * @param subPromoType the value for UNIORDER.ORDER_INFO.SUB_PROMO_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setSubPromoType(String subPromoType) {
        this.subPromoType = subPromoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CANCEL_DATE
     *
     * @return the value of UNIORDER.ORDER_INFO.CANCEL_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Date getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CANCEL_DATE
     *
     * @param cancelDate the value for UNIORDER.ORDER_INFO.CANCEL_DATE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.VIP_CODE
     *
     * @return the value of UNIORDER.ORDER_INFO.VIP_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getVipCode() {
        return vipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.VIP_CODE
     *
     * @param vipCode the value for UNIORDER.ORDER_INFO.VIP_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setVipCode(String vipCode) {
        this.vipCode = vipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.CALL_CONFIRM_STATUS
     *
     * @return the value of UNIORDER.ORDER_INFO.CALL_CONFIRM_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCallConfirmStatus() {
        return callConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.CALL_CONFIRM_STATUS
     *
     * @param callConfirmStatus the value for UNIORDER.ORDER_INFO.CALL_CONFIRM_STATUS
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCallConfirmStatus(String callConfirmStatus) {
        this.callConfirmStatus = callConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.TRAVEL_ORDER_NO
     *
     * @return the value of UNIORDER.ORDER_INFO.TRAVEL_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public Long getTravelOrderNo() {
        return travelOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.TRAVEL_ORDER_NO
     *
     * @param travelOrderNo the value for UNIORDER.ORDER_INFO.TRAVEL_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setTravelOrderNo(Long travelOrderNo) {
        this.travelOrderNo = travelOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.ORDER_TYPE
     *
     * @return the value of UNIORDER.ORDER_INFO.ORDER_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.ORDER_TYPE
     *
     * @param orderType the value for UNIORDER.ORDER_INFO.ORDER_TYPE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.COMPANY_CODE
     *
     * @return the value of UNIORDER.ORDER_INFO.COMPANY_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.COMPANY_CODE
     *
     * @param companyCode the value for UNIORDER.ORDER_INFO.COMPANY_CODE
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.RELATED_ORDER
     *
     * @return the value of UNIORDER.ORDER_INFO.RELATED_ORDER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getRelatedOrder() {
        return relatedOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.RELATED_ORDER
     *
     * @param relatedOrder the value for UNIORDER.ORDER_INFO.RELATED_ORDER
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setRelatedOrder(BigDecimal relatedOrder) {
        this.relatedOrder = relatedOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNIORDER.ORDER_INFO.ORI_ORDER_NO
     *
     * @return the value of UNIORDER.ORDER_INFO.ORI_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public BigDecimal getOriOrderNo() {
        return oriOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNIORDER.ORDER_INFO.ORI_ORDER_NO
     *
     * @param oriOrderNo the value for UNIORDER.ORDER_INFO.ORI_ORDER_NO
     *
     * @mbg.generated Wed Nov 22 16:11:20 CST 2017
     */
    public void setOriOrderNo(BigDecimal oriOrderNo) {
        this.oriOrderNo = oriOrderNo;
    }
}